---
title: "Longitudinal data"
date: "`r format(Sys.time(), '%d %B, %Y')`"
css: ../style.css
output: 
  html_document:
    number_sections: true
    toc: true
    toc_float: true
    toc_depth: 2
    code_folding: "hide"
editor_options: 
  chunk_output_type: console
---

# Longitudinal data

```{r eval=FALSE, include=FALSE}
rmarkdown::render(input = "production/prep-data-A.Rmd",output_format = "html_document",output_dir = ".")
```

```{r include=FALSE}
knitr::opts_chunk$set(warning = FALSE,message = FALSE, cache = FALSE,results = "hold")
knitr::opts_knit$set(root.dir = "../")
options(scipen=999)
rm(list=ls())
options(knitr.kable.NA = '')
```

```{r}
library(sjPlot)
library(dplyr)
library(tidyr)
library(lavaan)
library(stargazer)
library(corrplot)
library(psych)
library(knitr)
library(kableExtra)
```

```{r}
w01 <- sjlabelled::read_spss("input/data/original/Estudio_3_ola1.sav",verbose = F)
w02 <- sjlabelled::read_spss("input/data/original/Estudio_3_ola2.sav",verbose = F)
w03 <- sjlabelled::read_spss("input/data/original/Estudio_3_ola3.sav",verbose = F)
```

```{r}
table(w01$Intro,exclude=NULL) # (2) 221 no aceptan, (1) 2236 aceptan

w01a <- filter(w01,Intro==1) # Elimina los que no aceptan
table(w01a$Intro,exclude=NULL) # 2236 

# Variables para ver si finalizo encuesta
table(w01a$Finished,exclude=NULL) # (1) 2100 finalizan, (0) 136 no terminan

w01b <- filter(w01a,Finished==1) # Elimina los que no aceptan
table(w01b$Intro,exclude=NULL) # 2100
```

```{r}
table(w02$Intro,exclude=NULL) # (2)  no aceptan, (1)  aceptan

w02a <- filter(w02,Intro==1) # Elimina los que no aceptan
table(w02a$Intro,exclude=NULL) # 

# Variables para ver si finalizo encuesta
table(w02a$Finished,exclude=NULL) # (1)  finalizan, (0)  no terminan

w02b <- filter(w02a,Finished==1) # Elimina los que no aceptan
table(w02b$Intro,exclude=NULL) # 
```

```{r}
table(w03$Finished==1)
w03b <- filter(w03,Finished==1) # Elimina los que no aceptan
dim(w03b)
```


```{r}
w01b$ID<- stringr::str_split_fixed(w01b$ticket,"_", 4)[,1] # En la variable ticket el primer código es el ID, todo lo demás se borra
w02b$ID <- stringr::str_split_fixed(w02b$ticket, "_", 4)[,1] 

w03b$ID <- stringr::str_split_fixed(w03b$ticket, "_", 4)[,1] 
```

## prepare wave01

```{r}
w01c <- w01b 
w01c$grupo <- NA
w01c$grupo[w01c$FL_21_DO_merit_perc_pref_julio19v01==1] <- 1
w01c$grupo[w01c$FL_21_DO_merit_perc_pref_julio19v02==1] <- 2
w01c$grupo[w01c$FL_21_DO_merit_perc_pref_julio19v03==1] <- 3
w01c$perc_effort_w1 <- rowSums(w01c[,c(matches(match = "perc_effort",vars = names(w01c)))],na.rm = TRUE)
w01c$perc_talent_w1 <- rowSums(w01c[,c(matches(match = "perc_talent",vars = names(w01c)))],na.rm = TRUE)
w01c$perc_wpart_w1  <- rowSums(w01c[,c(matches(match = "perc_wpart" ,vars = names(w01c)))],na.rm = TRUE)
w01c$perc_netw_w1   <- rowSums(w01c[,c(matches(match = "perc_netw"  ,vars = names(w01c)))],na.rm = TRUE)

w01c$pref_effort_w1 <- rowSums(w01c[,c(matches(match = "pref_effort",vars = names(w01c)))],na.rm = TRUE)
w01c$pref_talent_w1 <- rowSums(w01c[,c(matches(match = "pref_talent",vars = names(w01c)))],na.rm = TRUE)
w01c$pref_wpart_w1  <- rowSums(w01c[,c(matches(match = "pref_wpart" ,vars = names(w01c)))],na.rm = TRUE)
w01c$pref_netw_w1   <- rowSums(w01c[,c(matches(match = "pref_netw"  ,vars = names(w01c)))],na.rm = TRUE)
w01c[w01c==0] <- NA
w01c <- w01c %>% select(ID,grupo,
                        perc_effort_w1,perc_talent_w1,perc_wpart_w1,perc_netw_w1,
                        pref_effort_w1,pref_talent_w1,pref_wpart_w1,pref_netw_w1,
                        sexo_w1=sexo,edad_w1=edad,edcep_w1=edcep)
#-----------------------------------------------------------------------#
skimr::skim(w01c)
```

## prepare wave02

```{r}
w02c <- w02b

w02c$treat <- NA
w02c$treat[w02c$FL_6_DO_Control==1] <- 1 
w02c$treat[w02c$FL_6_DO_Tratamiento==1] <- 2 
w02c$treat[w02c$FL_6_DO_Tratamiento_desigualdad==1] <- 3 

w02c$treat <- factor(w02c$treat,levels = c(1,2,3),labels = c("control","pobreza","desiguald"))

w02c <- w02c %>% rename(perc_effort_w2=meritv03_perc_effort,
                        perc_talent_w2=meritv03_perc_talent,
                        perc_wpart_w2 =meritv03_perc_wpart,
                        perc_netw_w2  =meritv03_perc_netw,
                        pref_effort_w2=meritv03_pref_effort,
                        pref_talent_w2=meritv03_pref_talent,
                        pref_wpart_w2 =meritv03_pref_wpart,
                        pref_netw_w2  =meritv03_pref_netw)

w02c <- w02c %>% select(ID,
                        perc_effort_w2,perc_talent_w2,perc_wpart_w2,perc_netw_w2,
                        pref_effort_w2,pref_talent_w2,pref_wpart_w2,pref_netw_w2,
                        sexo_w2=sexo,edad_w2=edad,edcep_w2=edcep, treat)

#-----------------------------------------------------------------------#
skimr::skim(w02c)
```

## prepare wave03

```{r}
w03c <- w03b

w03c <- w03c %>% rename(perc_effort_w3=meritv03_perc_effort,
                        perc_talent_w3=meritv03_perc_talent,
                        perc_wpart_w3 =meritv03_perc_wpart,
                        perc_netw_w3  =meritv03_perc_netw,
                        pref_effort_w3=meritv03_pref_effort,
                        pref_talent_w3=meritv03_pref_talent,
                        pref_wpart_w3 =meritv03_pref_wpart,
                        pref_netw_w3  =meritv03_pref_netw)
w03c <- w03c %>% select(ID,
                        perc_effort_w3,perc_talent_w3,perc_wpart_w3,perc_netw_w3,
                        pref_effort_w3,pref_talent_w3,pref_wpart_w3,pref_netw_w3,
                        sexo_w3=sexo,edad_w3=edad,edcep_w3=edcep)

#-----------------------------------------------------------------------#
skimr::skim(w03c)
```

## Merge wide data

```{r}
wide01 <- inner_join(x = w01c,y = w02c, by = "ID") # Solamente nos quedamos con casos en ambas olas 
dim(wide01) #en w01 y w02
```

```{r}
wide02 <- inner_join(x = wide01,y = w03c, by = "ID") # Solamente nos quedamos con casos en ambas olas 
dim(wide02) #en w01, w02 y w03
```

```{r}
skimr::skim(wide02)
```
 
```{r}
save(wide01,file = "input/data/proc/datawide.RData")
save(wide02,file = "input/data/proc/datawide_123.RData")
```

# Wide to long data

```{r}
library(datasets)
library(data.table)

wide <- setDT(wide02)

long01<- melt(wide,variable.name = "wave",
              measure = patterns("^perc_effort_","^perc_talent_","^perc_wpart_","^perc_netw_",
                                       "^pref_effort_","^pref_talent_","^pref_wpart_","^pref_netw_",
                                       "^sexo_","^edad_","^edcep_"),
              value.name = c("perc_effort","perc_talent","perc_wpart","perc_netw",
                             "pref_effort","pref_talent","pref_wpart","pref_netw",
                             "sexo","edad","edcep"))

```

```{r}
save(long01,file = "input/data/proc/datalong.RData")
```



