---
title: "Data preparation"
date: "`r format(Sys.time(), '%A %d %B %Y %X')`"
css: "../input/bib/style.css"
output:
  bookdown::html_document2:
    number_sections: true
    toc: true
    toc_float:
        collapsed: false
    toc_depth: 2
    code_folding: "hide"
editor_options:
  chunk_output_type: console
---

```{r eval=FALSE, include=FALSE}
rmarkdown::render(input = "production/prod_prep-data-A.Rmd",output_format = "html_document",output_dir = "production/");browseURL(url = "production/prod_prep-data-A.html")
```

```{r include=FALSE}
knitr::opts_chunk$set(warning = FALSE,message = FALSE, cache = FALSE,results = "hold")
knitr::opts_knit$set(root.dir = "../")
options(scipen=999)
rm(list=ls())
options(knitr.kable.NA = '')
```

load packages
```{r}
pacman::p_load(sjPlot,
               sjmisc, # several functions,ej read_stata
               descr,
               memisc,  # codebook
               psych, # cor2latex
               corrplot, # graph correlations
               lavaan,
               stargazer,
               semTools,
               plyr, # count
               dplyr,
               car, # recode
               ggplot2,
               Hmisc,
               tidyverse,
               data.table,
               stringr,
               countrycode,
               lme4,
               texreg,
               mice,
               ggrepel, # for scatter labels in sjp.scatter
               semPlot,
               haven,
               sjlabelled)
```

# Data 

```{r}
issp2009 <- read_dta("input/data/original/ZA5400_v4-0-0.dta")
```

## Data preparation
```{r }
# 0.DATA & LIBRARIES -------------------------------------------------------------------------------#
# 0.1 Libraries ------------------------------------------------------------------------------------#

# 0.2 Original data preparation --------------------------------------------------------------------#
# Check data
names(issp2009)
names(issp2009) <- tolower(names(issp2009))

# Check & generate IDs (v4: respondent, v5: country)
tapply(issp2009$v4, issp2009$v5, mean, na.rm = TRUE)
# Algunos paises (ej:826) tienen ids raros ...

# Generar nueva id secuencial individuos por país para merges
issp2009$id <- sequence(tabulate(issp2009$v5))
tapply(issp2009$id, issp2009$v5, mean, na.rm = TRUE) # ok
summary(issp2009$id)
issp2009$idtem = issp2009$v5 * 10000
issp2009$id = issp2009$idtem + issp2009$id

# End sec 0 ----------------------------------------------------------------------------------------#

# 1. Measuring perceptions (getting-ahead) --

# 1.1 Data preparation, gen getahead.rda

names(issp2009)
get_label(issp2009[8:18])

#  v6: wealthy family (c 8)
#  v7: educated parents (c 9)
#  v9: ambition c11
# v10: hard work c12
# v11: right people
# v12: political connections
# v14: race c16
# v16: gender c18
# IDs: v5 (country) & id (individual id)

# Recodes & relabels

# Rename
names(issp2009)
getahead = issp2009[, c("v6", "v7", "v9", "v10", "v11", "v12",
                        "v14", "v16", # get ahead
                        "v5", "id")]

getahead$wealthy = getahead$v6
getahead$pareduc = getahead$v7
getahead$ambition = getahead$v9
getahead$hwork = getahead$v10
getahead$people = getahead$v11
getahead$polcone = getahead$v12
getahead$race = getahead$v14
getahead$gender = getahead$v16

names(getahead)
getahead = getahead[-c(1:8)]


# recode values 8 9 to NA
freq(getahead$wealthy)
getahead[3:10][getahead[3:10] > 5] <- NA
freq(getahead$gender) # check ok
summary(getahead)

# adjust labels
get_labels(getahead$wealthy)
getahead[, 3:10] <- set_na(x = getahead[, 3:10],na = c(8,9))
get_labels(getahead[3:10]) # check

# Dataset with original code for sjp.likert graph
getahead2 = getahead

# Reverse code for SEM models
getahead[3:10] = 6 - getahead[3:10]

# Generate variables with 3 values for getahead mess model categoric
names(getahead)
getahead_temp = subset(getahead[c(2, 3:10)])
names(getahead_temp)
getahead_temp[2:9][getahead_temp[2:9] <  4] <- 3
freq(getahead_temp$hwork)
freq(getahead$hwork)
colnames(getahead_temp) = paste("c3", colnames(getahead_temp),
                                sep = "")
names(getahead_temp)[names(getahead_temp) == "c3id"] <- "id"
getahead_temp2 = merge(getahead, getahead_temp, by = c("id"))
names(getahead_temp2) # ok
getahead = getahead_temp2

view_df(getahead)
# Save object
save(getahead, file = "input/data/proc/getahead.rda")
```

```{r}	    
# 2. MEASURING BELIEFS (detearn) ---------- -#

# 2.1 Data preparation, detearn.rda -----#

names(issp2009)
detearn = issp2009[, c("v47", "v48", "v49", "v50", "v51",
                       "v52", "v5", "id")]

detearn$respons 	= detearn$v47
detearn$yeduc  	  = detearn$v48
detearn$family    = detearn$v49
detearn$child     = detearn$v50
detearn$welljob   = detearn$v51
detearn$hardjob   = detearn$v52

names(detearn)
detearn = detearn[-c(1:6)]

view_df(detearn,show.frq = T)
# recode values 8 9 to NA
summary(detearn)
freq(detearn$respons)
detearn[3:8][detearn[3:8] > 5] <- NA
freq(detearn$respons) # check ok

# Out Portugal (no answer in well job item)
detearn[which(detearn$v5 == 620), ] = NA

# adjust labels ###PROB PORTUCAL!!!
get_labels(detearn)
detearn[, 3:8] <- set_na(detearn[, 3:8],na =  c(8, 9)) 
# detearn$welljob<- set_na(detearn$welljob,na = c(1)) 
summary(detearn)
freq(detearn$welljob) ## prob portugal
detearn$welljob[detearn$welljob == 0] = NA
get_labels(detearn$welljob)
# labels(detearn$welljob) = labels(detearn$respons)### PROB NOT SOLVED

# Dataset with original code for sjp.likert graph
detearn2 = detearn

# Reverse code for SEM models
detearn[3:8] = 6 - detearn[3:8]
freq(detearn$respons)

# Save object
save(detearn, file = "input/data/proc/detearn.rda")
```

```{r}
merit_per_pref = merge(getahead, detearn, by = c("id", "v5"))
save(merit_per_pref, file = "input/data/proc/merit_per_pref.rda")
```

