---
title: "Pre-reg, scale perception meritocracy"
author:
- Luis Maldonado
- Juan Carlos Castillo
- Julio Iturra
- Jorge Atria
- Francisco Meneses
date: "13-11-2019"
output:
  html_document:
    theme: flatly
    highlight: tango
    toc: true
    toc_float: true
    toc_depth: 2
    number_sections: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Research questions

* How valid is a measurement model for the perception of 4-factor meritocracy, which is grouped into: a first-order   factor related to meritocracy and a second-order factor referred to inequalities of opportunity?


# General description and hypothesis

To measure the ideals of meritocracy, it is essential to differentiate preferences (i.e. what is considered desirable) and perceptions (i.e. how reality is believed to be) (duru-bellat, 2012). This work focuses on the perceptions of meritocracy.

Although a group of authors has measured the perception of meritocracy as if the perception of inequality of opportunities were the  side opposite of the continuum (Kunovich, 2007; Newman, 2015), others have shown that both concepts are rather different dimensions(Reynolds , 2014). Following this evidence, we chose to model both constructs as distinct latent variables. Different types of inequalities such as origin, contact or discrimination, cannot be considered in a single factor, since they refer to different realities and perceptions, therefore, it is consistent that they are independent latent variables. We also consider the existence of a latent second order variable, referring to the belief of inequality of opportunities in general.

Consistently, we consider that questions regarding meritocratic preferences will be grouped into two factors, meritocratic preferences and non-meritocratic preferences.

Additionally, it is important to mention that we will exploratoryly test the relationship between the “get a head” questions and questions that refer to whether “In Chile, people are rewarded or manage to succeed according to different qualities (i.e., hardworking, talented, with contacts)”.


* H1. The perception of meritocracy is a factor in the drift of the importance attributed to talent and the effort to get ahead in life.
* H2. The factors of family origin, contacts and discrimination are grouped into a second order factor that relates to non-meritocratic perceptions.
* H3. Preferences are also grouped into meritocratic and non-meritocratic preferences.
* H4 (exploratory) the way in which the perception of inequality of opportunities is asked influences the perception declared by the interviewees.

# Type of study

The present study is of an observational type focused on the measurement of the meritocracy preception variable. This study is part of an experimental study, applied online, which will be longitudinal panel type, that is, the same subjects will be surveyed 3 different occasions. The subjects will be randomly selected to be assigned to a placebo or to either of the two experimental procedures (change of poverty in Chile or international comparison of inequality)
To access the cases we turn to the Netquest survey company, which has coverage in several Latin American countries.


# Sample

## Detailed data and explanations of its use.

The Sample that will be necessary for this study has not yet been produced, nor has it begun its field work. However, in order to test the online questionnaire and the functionality of the quota offered by the Qualtrics platform, two previous studies have been carried out. The subjects participated in these two opportunities are excluded to the central sample, which corresponds to the 3-wave panel study.
These data from the two pilot studies were used for methodological decisions, descriptive stadistics, correlations and confirmation tests.
Due to the above, although the definitive sample has not yet been produced and therefore has not been explored, it is responsible to say, in addition to the review of previous research and international databases, it has some notions of the relationship among the variables product of the analysis of the previous samples



## Magnitude of the sample and explanation of the magnitude.

A representative sample of the large cities of Chile (Gran Santiago, Valparaíso-Viña del Mar, Concepción and Antofagasta) is expected, which will have an initial number for the first wave of 2100 cases, which are expected to be at least 1800 in the second wave. From the second to the third wave it has been considered as “free fall” that is, we are not sure of the retention rate of the interviewees.
The sample size was calculated from power analysis that used information from the pilot study that was applied in June 2019. This pilot study consisted of an online experiment applied to 949 subjects, randomly separating participants to two stimuli and a placebo, leaving a third of the sample in each condition. From these data, the low power of a two-tailed test was calculated, considering an average treatment effect of 0.26, with a standard deviation of the result of the treatment group of 1.23 and a significance level of 0.05. Based on multiple comparison correlations (Bonferroni), we adjusted alpha for six tests (three results * two comparisons between conditions and placebo). The results indicated that the number of subjects exposed to each stimulus should be 580, so we will work with three samples of 600 cases, which gives us a total of 1800 cases for the second wave in which the experiment will be applied. To guarantee the above and in consideration of a high non-response rate, we will start with a sample of 2100 subjects.

### Data collection procedure:
To access this target population, a company has been hired dedicated to the online surveys that will be in charge of getting the respondents. These will be invited to participate in the survey under the incentive provided by the external company. Respondents have 4 business days to answer the survey, with a maximum of 20 minutes per survey. In order to achieve greater representativeness of the sample, the quota method will be used, that is, the program will only allow respondents to respond while more people with their demographic characteristics are required. The quotas used were age, sex and education. It should be noted that the time between wave and wave is between 7 and 9 days.

### Stop Rule:
The rule of detention is to reach the number of respondents indicated, adjusted to the corresponding quotas. However, there may be modifications depending on the contingencies of the field work, depending on the response rates.

# Variables to use:
The variables used for the perception factor of meritocracy are:

* Para surgir en la vida, ¿cuán importante cree
usted que es?
    + Tener ambición
    + El trabajo duro

On the other hand, the questions related to inequality of opportunities are:

* Para surgir en la vida, ¿cuán importante cree
usted que es?
    + provenir de una familia rica o con muchos recursos
    + Tener padres con altos niveles de educación
    + Conocer a las personas adecuadas
    + Tener contactos políticos
    + La raza u origen étnico de las personas
    + El sexo de las personas, ser hombre o mujer

The items of preferences are:

* ¿En qué medida se encuentra usted de acuerdo o en desacuerdo con cada una de las siguientes afirmaciones?
    + Quienes más se esfuerzan deberían obtener mayores recompensas que quienes se esfuerzan menos
    + Quienes poseen más talento deberían obtener mayores recompensas que quienes tienen menos talento
    + Está bien que quienes tienen padres ricos salgan adelante
    + Está bien que quienes tienen buenos contactos salgan adelante

The questions that will be used for the exploratory analysis indicated are:

* ¿En qué medida se encuentra usted de acuerdo o en
desacuerdo con cada una de las siguientes
afirmaciones? En Chile,
    + Quienes más se esfuerzan logran obtener mayores recompensas.
    + Quienes tienen más talento logran obtener mayores recompensas.
    + Las personas con padres ricos logran salir adelante.
    + Los que tienen buenos contactos logran salir adelante.

### Variable manipulation

The variables will be worked on the same scale in which they were asked, without resorting to manipulations of the variables to assess the validity of the measurement model.

### Indexes

The investigation of the validity of this scale does not resort to indices intended to represent the perception of meritocracy in an observed way, but rather confirmatory factor analysis will be used to estimate the value of the latent variables underlying the indicators.

### Blinding of information

No special blinding is used for this study.

### Randomization
To avoid the existence of biases in the order of the questions, they have been randomized within a thematic block of questions, so, randomly, people answer questions in different orders regarding their perception of meritocracy.

# Analysis plan
To evaluate these hypotheses, confirmatory factor analysis will be used, since we have strong theory regarding the ordering of the factors. In addition, exploratory factor analysis will be used to evaluate the exploratory hypothesis indicated. The Lavaan R package will be used.

### Inference criteria,
The values that will be used as evaluation criteria for the goodness of the adjustment of the model were taken from the proposal of Ruiz, Partdo and San Martin (2010) and are the following:
*Chi-square:> 0.05
*Chi-square ratio:> 3
*Comparative adjustment goodness index (CFI):> 0.95
*Tucker-Lewis Index (TLI):> 0.95
*Root of the average squared residual approximation <0.08.

### Data Exclusion
All cases will be used as long as they do not show missing valuesin any of the items on the scale. No imputation criteria will be used.

### Ethics. JI
The experiment and survey instruments are approved by the IRB of the University of Chile.

# bibliography

Ruiz, M., Pardo, A. & San Martín, R. (2010). Modelos de Ecuaciones Estructurales. -Papeles del psicólogo, 31-(1), pp. 34-45.

Duru-Bellat, M., & Tenret, E. (2012). Who’s for Meritocracy? Individual and Contextual Variations in the Faith. Chicago Journal, 56(2), 223-247.

Kunovich, S., & Slomczynski, K. M. (2007). Systems of Distribution and a Sense of Equity: A Multilevel Analysis of Meritocratic Attitudes in
Post-industrial Societies. European Sociological Review, 23(5), 649–663. doi:10.1093/esr/jcm026

Newman, B. J., Johnston, C. D., & Lown, P. L. (2014). False Consciousness or Class Awareness? Local Income Inequality, Personal Economic Position, and Belief in American Meritocracy. American Journal of Political Science, 59(2), 326-340. doi:10.1111/ajps.12153

Reynolds, J., & Xian, H. (2014). Perceptions of meritocracy in the land of opportunity. Research in Social Stratification and Mobility, 36, 121–137. doi:10.1016/j.rssm.2014.03.001
