---
title: "PPM-S"
csl: "../input/bib/apa6.csl"
bibliography: "../input/bib/zlibrary.bib"
author: " "
output:
    html_document:
        smart: false
---




## This is the project website for the development and testing of the Perceptions and Preferences for Meritocracy Scale.

last website update: `r format(Sys.time(), "%A %d %B %Y %X")`

### Authors:

- Juan Carlos Castillo, Departamento de Sociología, Universidad de Chile. [juancastillov@uchile.cl](juancastillov@uchile.cl), [jc-castillo.com](http://jc-castillo.com/)
- Julio Iturra, Centro de Estudios de Conflicto y Cohesión Social - COES
- Francisco Meneses, Departamento de Sociología, Universidad de Chile.
- Luis Maldonado, Instituto de Sociología, Pontificia Universidad Católica de Chile

### In brief:

Based on a previous paper that proposed a distinction between perceptions and preferences for meritocracy and tested it with secondary survet data [[@Castilloetal2019]](http://revintsociologia.revistas.csic.es/index.php/revintsociologia/article/view/1017), we designed and tested a scale in a longitudinal three-wave online panel in Chile (N=1.422, final wave) through confirmatory factor analysis and measurement invariance procedures.


### Structure of the project website:

- Pre-analysis: here is the description of the pre-registration of the analysis plan in the Open Science Framework, you can see it directly [here:](https://osf.io/z45y2). To cite: Castillo, J. C., Iturra, J. C., Rivas, F. J. M., & Maldonado, L. (2019, November 21). Perceptions and Preferences for Meritocracy Scale  (PPM-S). Retrieved from osf.io/z45y2

- The other three tabs follow the logic of the [IPO protocol](https://github.com/juancarloscastillo/ipo) for academic workflows, based on three main components = **I**nput -> **P**roduction -> **O**utput. Here we show only one the main parts of each component: Data -> Analysis -> Paper. The complete reproducible files are in the [Github repo: https://juancarloscastillo.github.io/merit-scale/](https://juancarloscastillo.github.io/merit-scale/)

  - _Data_: pre-processing and general descriptives
  - _Analysis_: CFA (Confirmatory Factor Analysis) and measurement invariance
  - _Paper_: final output


## References
