<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Analysis</title>

<script src="site_libs/header-attrs-2.1/header-attrs.js"></script>
<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/flatly.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>

<link rel="stylesheet" href="..\input\bib\style.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 60px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h2 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h3 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h4 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h5 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h6 {
  padding-top: 65px;
  margin-top: -65px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Measuring meritocratic perceptions and beliefs</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="preanalisis.html">Preanalisis</a>
</li>
<li>
  <a href="paper.html">Paper</a>
</li>
<li>
  <a href="prod_prep-data-A.html">Data</a>
</li>
<li>
  <a href="prod_analysis-cfa.html">Analysis</a>
</li>
<li>
  <a href="preanalisis.pdf">
    <span class="fa fa-file-pdf"></span>
     
    PDF
  </a>
</li>
<li>
  <a href="https://github.com/juancarloscastillo/merit-scale">
    <span class="fa fa-github fa-lg"></span>
     
    
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">

<div class="btn-group pull-right">
<button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Analysis</h1>
<h4 class="date">20 marzo, 2020</h4>

</div>


<div id="análisis-ppm-s" class="section level1" number="1">
<h1 number="1"><span class="header-section-number">1</span> Análisis PPM-S</h1>
</div>
<div id="wave-01" class="section level1" number="2">
<h1 number="2"><span class="header-section-number">2</span> Wave 01</h1>
<pre class="r"><code>library(sjPlot)
library(dplyr)
library(lavaan)
library(stargazer)
library(corrplot)
library(psych)
library(knitr)
library(kableExtra)</code></pre>
<pre class="r"><code>data01 &lt;- sjlabelled::read_spss(path = &quot;input/data/original/Estudio_3_ola1.sav&quot;,verbose = FALSE)

dat01 &lt;- data01 %&gt;% filter(Intro==1,Finished==1) %&gt;% select(starts_with(&quot;meritv01&quot;)) %&gt;% na.omit()
dat02 &lt;- data01 %&gt;% filter(Intro==1,Finished==1) %&gt;% select(starts_with(&quot;meritv02&quot;)) %&gt;% na.omit()
dat03 &lt;- data01 %&gt;% filter(Intro==1,Finished==1) %&gt;% select(starts_with(&quot;meritv03_p&quot;)) %&gt;% na.omit()

# - Nos quedamos solamente con los casos que ACEPTARON participar y terminaron el cuestionario.
# - Para dejar una base que contenga solamente los casos que tienen información completa en los ítems usamos na.omit()

dat04 &lt;- data01 %&gt;% filter(Intro==1) %&gt;%
  select(starts_with(&quot;meritv01&quot;),
         starts_with(&quot;meritv02&quot;),
         starts_with(&quot;meritv03_p&quot;),
         starts_with(&quot;FL_21_DO&quot;)) 
dat04$grupo &lt;- NA
dat04$grupo[dat04$FL_21_DO_merit_perc_pref_julio19v01==1] &lt;- 1
dat04$grupo[dat04$FL_21_DO_merit_perc_pref_julio19v02==1] &lt;- 2
dat04$grupo[dat04$FL_21_DO_merit_perc_pref_julio19v03==1] &lt;- 3
dat04$perc_effort &lt;- rowSums(dat04[,c(matches(match = &quot;perc_effort&quot;,vars = names(dat04)))],na.rm = TRUE)
dat04$perc_talent &lt;- rowSums(dat04[,c(matches(match = &quot;perc_talent&quot;,vars = names(dat04)))],na.rm = TRUE)
dat04$perc_wpart  &lt;- rowSums(dat04[,c(matches(match = &quot;perc_wpart&quot; ,vars = names(dat04)))],na.rm = TRUE)
dat04$perc_netw   &lt;- rowSums(dat04[,c(matches(match = &quot;perc_netw&quot;  ,vars = names(dat04)))],na.rm = TRUE)

dat04$pref_effort &lt;- rowSums(dat04[,c(matches(match = &quot;pref_effort&quot;,vars = names(dat04)))],na.rm = TRUE)
dat04$pref_talent &lt;- rowSums(dat04[,c(matches(match = &quot;pref_talent&quot;,vars = names(dat04)))],na.rm = TRUE)
dat04$pref_wpart  &lt;- rowSums(dat04[,c(matches(match = &quot;pref_wpart&quot; ,vars = names(dat04)))],na.rm = TRUE)
dat04$pref_netw   &lt;- rowSums(dat04[,c(matches(match = &quot;pref_netw&quot;  ,vars = names(dat04)))],na.rm = TRUE)
dat04[dat04==0] &lt;- NA</code></pre>
<div id="version-01-fixed-order-by-perception-preferences-n697" class="section level2" number="2.1">
<h2 number="2.1"><span class="header-section-number">2.1</span> Version 01: Fixed order by perception / preferences (N=697)</h2>
<ol style="list-style-type: decimal">
<li>Percepcion esfuerzo</li>
<li>Percepcion talento</li>
<li>Percepcion familia rica</li>
<li>Percepcion redes</li>
<li>Preferencia esfuerzo</li>
<li>Preferencia talento</li>
<li>Preferencia familia rica</li>
<li>Preferencia redes</li>
</ol>
<table style="text-align:center">
<tr>
<td colspan="8" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
Statistic
</td>
<td>
N
</td>
<td>
Mean
</td>
<td>
St. Dev.
</td>
<td>
Min
</td>
<td>
Pctl(25)
</td>
<td>
Pctl(75)
</td>
<td>
Max
</td>
</tr>
<tr>
<td colspan="8" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
meritv01_perc_effort
</td>
<td>
697
</td>
<td>
3.164
</td>
<td>
1.360
</td>
<td>
1
</td>
<td>
2
</td>
<td>
4
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
meritv01_perc_talent
</td>
<td>
697
</td>
<td>
2.981
</td>
<td>
1.122
</td>
<td>
1
</td>
<td>
2
</td>
<td>
4
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
meritv01_perc_wpart
</td>
<td>
697
</td>
<td>
3.603
</td>
<td>
1.353
</td>
<td>
1
</td>
<td>
3
</td>
<td>
5
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
meritv01_perc_netw
</td>
<td>
697
</td>
<td>
3.740
</td>
<td>
1.255
</td>
<td>
1
</td>
<td>
3
</td>
<td>
5
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
meritv01_pref_effort
</td>
<td>
697
</td>
<td>
3.908
</td>
<td>
1.225
</td>
<td>
1
</td>
<td>
3
</td>
<td>
5
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
meritv01_pref_talent
</td>
<td>
697
</td>
<td>
3.268
</td>
<td>
1.168
</td>
<td>
1
</td>
<td>
3
</td>
<td>
4
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
meritv01_pref_wpart
</td>
<td>
697
</td>
<td>
2.555
</td>
<td>
1.117
</td>
<td>
1
</td>
<td>
2
</td>
<td>
3
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
meritv01_pref_netw
</td>
<td>
697
</td>
<td>
2.337
</td>
<td>
1.057
</td>
<td>
1
</td>
<td>
1
</td>
<td>
3
</td>
<td>
5
</td>
</tr>
<tr>
<td colspan="8" style="border-bottom: 1px solid black">
</td>
</tr>
</table>
<pre class="r"><code>cor01&lt;-polychoric(dat01)
corrplot(cor01$rho,method = &quot;color&quot; ,type = &quot;upper&quot;, order = &quot;hclust&quot;, tl.col = &quot;black&quot;, tl.srt = 45,addCoef.col = &quot;black&quot;,diag = FALSE)</code></pre>
<p><img src="prod_analysis-cfa_files/figure-html/correlacion%20v01-1.png" width="672" /></p>
<pre class="r"><code>model01 &lt;- &#39;
perc_merit=~meritv01_perc_effort+meritv01_perc_talent 
perc_nmerit=~meritv01_perc_wpart+meritv01_perc_netw  
pref_merit=~meritv01_pref_effort+meritv01_pref_talent 
pref_nmerit=~meritv01_pref_wpart+meritv01_pref_netw&#39;

fit1_c &lt;- cfa(model = model01,data = dat01,estimator=&quot;MLR&quot;) # Continuo/ estimador ML Robust

fit1_o &lt;- cfa(model = model01,data = dat01,
            ordered = c(&quot;meritv01_perc_effort&quot;,&quot;meritv01_perc_talent&quot;,
                        &quot;meritv01_perc_wpart&quot;,&quot;meritv01_perc_netw&quot;,
                        &quot;meritv01_pref_effort&quot;,&quot;meritv01_pref_talent&quot;,
                        &quot;meritv01_pref_wpart&quot;,&quot;meritv01_pref_netw&quot;))

#---------------------------------------------------#
# #summary(fit1_c,standardized=TRUE, fit.measures=TRUE)}
fitmeasures(fit1_c)[c(&quot;chisq.scaled&quot;,&quot;df&quot;,&quot;cfi&quot;,&quot;cfi.scaled&quot;,&quot;cfi.robust&quot;,&quot;rmsea&quot;,&quot;rmsea.scaled&quot;,&quot;rmsea.robust&quot;)]
semPlot::semPaths(object = fit1_c,what = &quot;std&quot;,thresholds = FALSE, intercepts = FALSE,fade=FALSE, curve = 1.5)</code></pre>
<p><img src="prod_analysis-cfa_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<pre class="r"><code># #summary(fit1_o,standardized=TRUE, fit.measures=TRUE)
fitmeasures(fit1_o)[c(&quot;chisq.scaled&quot;,&quot;df&quot;,&quot;cfi&quot;,&quot;cfi.scaled&quot;,&quot;cfi.robust&quot;,&quot;rmsea&quot;,&quot;rmsea.scaled&quot;,&quot;rmsea.robust&quot;)]
semPlot::semPaths(object = fit1_o,what = &quot;std&quot;,thresholds = FALSE, intercepts = FALSE,fade=FALSE, curve = 1.5)</code></pre>
<p><img src="prod_analysis-cfa_files/figure-html/unnamed-chunk-6-2.png" width="672" /></p>
<pre><code>## chisq.scaled           df          cfi   cfi.scaled   cfi.robust        rmsea rmsea.scaled 
##  42.93480226  14.00000000   0.97948028   0.97736086   0.98021257   0.05812794   0.05445401 
## rmsea.robust 
##   0.05695600 
## chisq.scaled           df          cfi   cfi.scaled   cfi.robust        rmsea rmsea.scaled 
##  46.11414265  14.00000000   0.99763575   0.99207488           NA   0.03794574   0.05740894 
## rmsea.robust 
##           NA</code></pre>
<blockquote>
<p><em>#summary</em>: good fit, heywood case item 8.</p>
</blockquote>
</div>
<div id="version-02-fixed-order-by-topic-n706" class="section level2" number="2.2">
<h2 number="2.2"><span class="header-section-number">2.2</span> Version 02: Fixed order, by topic (N=706)</h2>
<ol style="list-style-type: decimal">
<li>Percepcion esfuerzo</li>
<li>Preferencia esfuerzo</li>
<li>Percepcion talento</li>
<li>Preferencia talento</li>
<li>Percepcion familia rica</li>
<li>Preferencia familia rica</li>
<li>Percepcion redes</li>
<li>Preferencia redes</li>
</ol>
<table style="text-align:center">
<tr>
<td colspan="8" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
Statistic
</td>
<td>
N
</td>
<td>
Mean
</td>
<td>
St. Dev.
</td>
<td>
Min
</td>
<td>
Pctl(25)
</td>
<td>
Pctl(75)
</td>
<td>
Max
</td>
</tr>
<tr>
<td colspan="8" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
meritv02_perc_effort
</td>
<td>
706
</td>
<td>
3.105
</td>
<td>
1.399
</td>
<td>
1
</td>
<td>
2
</td>
<td>
4
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
meritv02_pref_effort
</td>
<td>
706
</td>
<td>
3.741
</td>
<td>
1.339
</td>
<td>
1
</td>
<td>
3
</td>
<td>
5
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
meritv02_perc_talent
</td>
<td>
706
</td>
<td>
3.035
</td>
<td>
1.111
</td>
<td>
1
</td>
<td>
2
</td>
<td>
4
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
meritv02_pref_talent
</td>
<td>
706
</td>
<td>
3.146
</td>
<td>
1.149
</td>
<td>
1
</td>
<td>
2
</td>
<td>
4
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
meritv02_perc_wpart
</td>
<td>
706
</td>
<td>
3.661
</td>
<td>
1.364
</td>
<td>
1
</td>
<td>
3
</td>
<td>
5
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
meritv02_pref_wpart
</td>
<td>
706
</td>
<td>
2.742
</td>
<td>
1.209
</td>
<td>
1
</td>
<td>
2
</td>
<td>
4
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
meritv02_perc_netw
</td>
<td>
706
</td>
<td>
3.728
</td>
<td>
1.218
</td>
<td>
1
</td>
<td>
3
</td>
<td>
5
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
meritv02_pref_netw
</td>
<td>
706
</td>
<td>
2.385
</td>
<td>
1.109
</td>
<td>
1
</td>
<td>
1
</td>
<td>
3
</td>
<td>
5
</td>
</tr>
<tr>
<td colspan="8" style="border-bottom: 1px solid black">
</td>
</tr>
</table>
<pre class="r"><code>cor02&lt;-polychoric(dat02)
corrplot(cor02$rho,method = &quot;color&quot;, type = &quot;upper&quot;, order = &quot;hclust&quot;, tl.col = &quot;black&quot;, tl.srt = 45,addCoef.col = &quot;black&quot;,diag = FALSE)</code></pre>
<p><img src="prod_analysis-cfa_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<pre class="r"><code>model02 &lt;- &#39;
perc_merit=~meritv02_perc_effort+meritv02_perc_talent 
perc_nmerit=~meritv02_perc_wpart+meritv02_perc_netw  
pref_merit=~meritv02_pref_effort+meritv02_pref_talent 
pref_nmerit=~meritv02_pref_wpart+meritv02_pref_netw&#39;

fit2_c &lt;- cfa(model = model02,data = dat02,estimator=&quot;MLR&quot;) # Continuo/ estimador ML Robust

fit2_o &lt;- cfa(model = model02,data = dat02,ordered = c(&quot;meritv02_perc_effort&quot;,&quot;meritv02_perc_talent&quot;,
                                                     &quot;meritv02_perc_wpart&quot;,&quot;meritv02_perc_netw&quot;,
                                                     &quot;meritv02_pref_effort&quot;,&quot;meritv02_pref_talent&quot;,
                                                     &quot;meritv02_pref_wpart&quot;,&quot;meritv02_pref_netw&quot;))

#---------------------------------------------------#
#summary(fit2_c,standardized=TRUE, fit.measures=TRUE)
fitmeasures(fit2_c)[c(&quot;chisq.scaled&quot;,&quot;df&quot;,&quot;cfi&quot;,&quot;cfi.scaled&quot;,&quot;cfi.robust&quot;,&quot;rmsea&quot;,&quot;rmsea.scaled&quot;,&quot;rmsea.robust&quot;)]
semPlot::semPaths(object = fit2_c,what = &quot;std&quot;,thresholds = FALSE, intercepts = FALSE,fade=FALSE, curve = 1.5)</code></pre>
<p><img src="prod_analysis-cfa_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<pre class="r"><code>#summary(fit2_o,standardized=TRUE, fit.measures=TRUE)
fitmeasures(fit2_o)[c(&quot;chisq.scaled&quot;,&quot;df&quot;,&quot;cfi&quot;,&quot;cfi.scaled&quot;,&quot;cfi.robust&quot;,&quot;rmsea&quot;,&quot;rmsea.scaled&quot;,&quot;rmsea.robust&quot;)]
semPlot::semPaths(object = fit2_o,what = &quot;std&quot;,thresholds = FALSE, intercepts = FALSE,fade=FALSE, curve = 1.5)</code></pre>
<p><img src="prod_analysis-cfa_files/figure-html/unnamed-chunk-9-2.png" width="672" /></p>
<pre><code>## chisq.scaled           df          cfi   cfi.scaled   cfi.robust        rmsea rmsea.scaled 
## 100.06185323  14.00000000   0.92567916   0.91208862   0.92577394   0.09562704   0.09331232 
## rmsea.robust 
##   0.09530656 
## chisq.scaled           df          cfi   cfi.scaled   cfi.robust        rmsea rmsea.scaled 
## 101.48249122  14.00000000   0.98421904   0.96229187           NA   0.07128592   0.09414603 
## rmsea.robust 
##           NA</code></pre>
<blockquote>
<p><strong>NOTA</strong>: bad fit, heywood en estimación DWLS</p>
</blockquote>
</div>
<div id="version-03-random-order-n697" class="section level2" number="2.3">
<h2 number="2.3"><span class="header-section-number">2.3</span> Version 03: Random order (N=697)</h2>
<table style="text-align:center">
<tr>
<td colspan="8" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
Statistic
</td>
<td>
N
</td>
<td>
Mean
</td>
<td>
St. Dev.
</td>
<td>
Min
</td>
<td>
Pctl(25)
</td>
<td>
Pctl(75)
</td>
<td>
Max
</td>
</tr>
<tr>
<td colspan="8" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
meritv03_perc_effort
</td>
<td>
697
</td>
<td>
3.329
</td>
<td>
1.370
</td>
<td>
1
</td>
<td>
2
</td>
<td>
5
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
meritv03_perc_talent
</td>
<td>
697
</td>
<td>
3.072
</td>
<td>
1.245
</td>
<td>
1
</td>
<td>
2
</td>
<td>
4
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
meritv03_perc_wpart
</td>
<td>
697
</td>
<td>
3.722
</td>
<td>
1.360
</td>
<td>
1
</td>
<td>
3
</td>
<td>
5
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
meritv03_perc_netw
</td>
<td>
697
</td>
<td>
3.900
</td>
<td>
1.235
</td>
<td>
1
</td>
<td>
3
</td>
<td>
5
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
meritv03_pref_effort
</td>
<td>
697
</td>
<td>
4.046
</td>
<td>
1.159
</td>
<td>
1
</td>
<td>
4
</td>
<td>
5
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
meritv03_pref_talent
</td>
<td>
697
</td>
<td>
3.339
</td>
<td>
1.229
</td>
<td>
1
</td>
<td>
2
</td>
<td>
4
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
meritv03_pref_wpart
</td>
<td>
697
</td>
<td>
2.770
</td>
<td>
1.189
</td>
<td>
1
</td>
<td>
2
</td>
<td>
4
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
meritv03_pref_netw
</td>
<td>
697
</td>
<td>
2.506
</td>
<td>
1.144
</td>
<td>
1
</td>
<td>
2
</td>
<td>
3
</td>
<td>
5
</td>
</tr>
<tr>
<td colspan="8" style="border-bottom: 1px solid black">
</td>
</tr>
</table>
<pre class="r"><code>cor03&lt;-polychoric(dat03)
corrplot(cor03$rho,method = &quot;color&quot;, type = &quot;upper&quot;, order = &quot;hclust&quot;, tl.col = &quot;black&quot;, tl.srt = 45,addCoef.col = &quot;black&quot;,diag = FALSE)</code></pre>
<p><img src="prod_analysis-cfa_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<pre class="r"><code>model03 &lt;- &#39;
perc_merit=~meritv03_perc_effort+meritv03_perc_talent 
perc_nmerit=~meritv03_perc_wpart+meritv03_perc_netw  
pref_merit=~meritv03_pref_effort+meritv03_pref_talent 
pref_nmerit=~meritv03_pref_wpart+meritv03_pref_netw&#39;

fit3_c &lt;- cfa(model = model03,data = dat03,estimator=&quot;MLR&quot;,std.lv=FALSE) # Continuo/ estimador ML Robust

fit3_o &lt;- cfa(model = model03,data = dat03,ordered = c(&quot;meritv03_perc_effort&quot;,&quot;meritv03_perc_talent&quot;,
                                                       &quot;meritv03_perc_wpart&quot;,&quot;meritv03_perc_netw&quot;,
                                                       &quot;meritv03_pref_effort&quot;,&quot;meritv03_pref_talent&quot;,
                                                       &quot;meritv03_pref_wpart&quot;,&quot;meritv03_pref_netw&quot;),std.lv=FALSE)
#---------------------------------------------------#
#summary(fit3_c,standardized=TRUE, fit.measures=TRUE)
fitmeasures(fit3_c)[c(&quot;chisq.scaled&quot;,&quot;df&quot;,&quot;cfi&quot;,&quot;cfi.scaled&quot;,&quot;cfi.robust&quot;,&quot;rmsea&quot;,&quot;rmsea.scaled&quot;,&quot;rmsea.robust&quot;)]
semPlot::semPaths(object = fit3_c,what = &quot;std&quot;,thresholds = FALSE, intercepts = FALSE,fade=FALSE, curve = 1.5)</code></pre>
<p><img src="prod_analysis-cfa_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<pre class="r"><code>#summary(fit3_o,standardized=TRUE, fit.measures=TRUE)
fitmeasures(fit3_o)[c(&quot;chisq.scaled&quot;,&quot;df&quot;,&quot;cfi&quot;,&quot;cfi.scaled&quot;,&quot;cfi.robust&quot;,&quot;rmsea&quot;,&quot;rmsea.scaled&quot;,&quot;rmsea.robust&quot;)]
semPlot::semPaths(object = fit3_o,what = &quot;std&quot;,thresholds = FALSE, intercepts = FALSE,fade=FALSE, curve = 1.5)</code></pre>
<p><img src="prod_analysis-cfa_files/figure-html/unnamed-chunk-12-2.png" width="672" /></p>
<pre><code>## chisq.scaled           df          cfi   cfi.scaled   cfi.robust        rmsea rmsea.scaled 
##   57.0584003   14.0000000    0.9519967    0.9424676    0.9523832    0.0686923    0.0664276 
## rmsea.robust 
##    0.0681436 
## chisq.scaled           df          cfi   cfi.scaled   cfi.robust        rmsea rmsea.scaled 
##  60.02456981  14.00000000   0.99183602   0.98040527           NA   0.05074320   0.06872682 
## rmsea.robust 
##           NA</code></pre>
<blockquote>
<p><strong>NOTA</strong>: fit not very goood (RMSEA .7), no heywood. Try tau-equivalence</p>
</blockquote>
<pre class="r"><code>model03.tau &lt;- &#39;
perc_merit=~ r1*meritv03_perc_effort+r1*meritv03_perc_talent 
perc_nmerit=~r2*meritv03_perc_wpart+ r2*meritv03_perc_netw  
pref_merit=~ r3*meritv03_pref_effort+r3*meritv03_pref_talent 
pref_nmerit=~r4*meritv03_pref_wpart+ r4*meritv03_pref_netw&#39;

fit3_c.tau &lt;- cfa(model = model03.tau,data = dat03,estimator=&quot;MLR&quot;,std.lv=FALSE) # Continuo/ estimador ML Robust

fit3_o.tau &lt;- cfa(model = model03.tau,data = dat03,ordered = c(&quot;meritv03_perc_effort&quot;,&quot;meritv03_perc_talent&quot;,
                                                               &quot;meritv03_perc_wpart&quot;,&quot;meritv03_perc_netw&quot;,
                                                               &quot;meritv03_pref_effort&quot;,&quot;meritv03_pref_talent&quot;,
                                                               &quot;meritv03_pref_wpart&quot;,&quot;meritv03_pref_netw&quot;), std.lv=FALSE)
#---------------------------------------------------#
#summary(fit3_c.tau,standardized=TRUE, fit.measures=TRUE)
fitmeasures(fit3_c.tau)[c(&quot;chisq.scaled&quot;,&quot;df&quot;,&quot;cfi&quot;,&quot;cfi.scaled&quot;,&quot;cfi.robust&quot;,&quot;rmsea&quot;,&quot;rmsea.scaled&quot;,&quot;rmsea.robust&quot;)]
semPlot::semPaths(object = fit3_c.tau,what = &quot;std&quot;,thresholds = FALSE, intercepts = FALSE,fade=FALSE, curve = 1.5)</code></pre>
<p><img src="prod_analysis-cfa_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<pre class="r"><code>#summary(fit3_o,standardized=TRUE, fit.measures=TRUE)
fitmeasures(fit3_o.tau)[c(&quot;chisq.scaled&quot;,&quot;df&quot;,&quot;cfi&quot;,&quot;cfi.scaled&quot;,&quot;cfi.robust&quot;,&quot;rmsea&quot;,&quot;rmsea.scaled&quot;,&quot;rmsea.robust&quot;)]
semPlot::semPaths(object = fit3_o.tau,what = &quot;std&quot;,thresholds = FALSE, intercepts = FALSE,fade=FALSE, curve = 1.5)</code></pre>
<p><img src="prod_analysis-cfa_files/figure-html/unnamed-chunk-13-2.png" width="672" /></p>
<pre><code>## chisq.scaled           df          cfi   cfi.scaled   cfi.robust        rmsea rmsea.scaled 
##  54.64691498  18.00000000   0.95176935   0.95103426   0.95471247   0.06072423   0.05404631 
## rmsea.robust 
##   0.05860871 
## chisq.scaled           df          cfi   cfi.scaled   cfi.robust        rmsea rmsea.scaled 
##  59.09776813  18.00000000   0.99254921   0.98250283           NA   0.04275195   0.05727542 
## rmsea.robust 
##           NA</code></pre>
<pre class="r"><code>rbind(fitmeasures(fit3_o)[c(&quot;chisq.scaled&quot;,&quot;df&quot;,&quot;cfi&quot;,&quot;cfi.scaled&quot;,&quot;cfi.robust&quot;,&quot;rmsea&quot;,&quot;rmsea.scaled&quot;,&quot;rmsea.robust&quot;)],
      fitmeasures(fit3_o.tau)[c(&quot;chisq.scaled&quot;,&quot;df&quot;,&quot;cfi&quot;,&quot;cfi.scaled&quot;,&quot;cfi.robust&quot;,&quot;rmsea&quot;,&quot;rmsea.scaled&quot;,&quot;rmsea.robust&quot;)])
anova(fit3_o,fit3_o.tau)</code></pre>
<pre><code>##      chisq.scaled df       cfi cfi.scaled cfi.robust      rmsea rmsea.scaled rmsea.robust
## [1,]     60.02457 14 0.9918360  0.9804053         NA 0.05074320   0.06872682           NA
## [2,]     59.09777 18 0.9925492  0.9825028         NA 0.04275195   0.05727542           NA
## Scaled Chi-Squared Difference Test (method = &quot;satorra.2000&quot;)
## 
## lavaan NOTE:
##     The &quot;Chisq&quot; column contains standard test statistics, not the
##     robust test that should be reported per model. A robust difference
##     test is a function of two standard (not robust) statistics.
##  
##            Df AIC BIC  Chisq Chisq diff Df diff Pr(&gt;Chisq)
## fit3_o     14         39.090                              
## fit3_o.tau 18         40.898     2.3387       4     0.6737</code></pre>
<blockquote>
<p><strong>NOTA:</strong> El modelo con igualdad de cargas factoriales no deteriora significativamente el ajuste del modelo.</p>
</blockquote>
</div>
<div id="version-04-muestra-completa-n2236" class="section level2" number="2.4">
<h2 number="2.4"><span class="header-section-number">2.4</span> Version 04: muestra completa (N=2236)</h2>
<table style="text-align:center">
<tr>
<td colspan="8" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
Statistic
</td>
<td>
N
</td>
<td>
Mean
</td>
<td>
St. Dev.
</td>
<td>
Min
</td>
<td>
Pctl(25)
</td>
<td>
Pctl(75)
</td>
<td>
Max
</td>
</tr>
<tr>
<td colspan="8" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
perc_effort
</td>
<td>
2,142
</td>
<td>
3.200
</td>
<td>
1.380
</td>
<td>
1.000
</td>
<td>
2.000
</td>
<td>
4.000
</td>
<td>
5.000
</td>
</tr>
<tr>
<td style="text-align:left">
perc_talent
</td>
<td>
2,141
</td>
<td>
3.024
</td>
<td>
1.161
</td>
<td>
1.000
</td>
<td>
2.000
</td>
<td>
4.000
</td>
<td>
5.000
</td>
</tr>
<tr>
<td style="text-align:left">
perc_wpart
</td>
<td>
2,141
</td>
<td>
3.660
</td>
<td>
1.361
</td>
<td>
1.000
</td>
<td>
3.000
</td>
<td>
5.000
</td>
<td>
5.000
</td>
</tr>
<tr>
<td style="text-align:left">
perc_netw
</td>
<td>
2,141
</td>
<td>
3.787
</td>
<td>
1.242
</td>
<td>
1.000
</td>
<td>
3.000
</td>
<td>
5.000
</td>
<td>
5.000
</td>
</tr>
<tr>
<td style="text-align:left">
pref_effort
</td>
<td>
2,141
</td>
<td>
3.894
</td>
<td>
1.254
</td>
<td>
1.000
</td>
<td>
3.000
</td>
<td>
5.000
</td>
<td>
5.000
</td>
</tr>
<tr>
<td style="text-align:left">
pref_talent
</td>
<td>
2,141
</td>
<td>
3.243
</td>
<td>
1.188
</td>
<td>
1.000
</td>
<td>
2.000
</td>
<td>
4.000
</td>
<td>
5.000
</td>
</tr>
<tr>
<td style="text-align:left">
pref_wpart
</td>
<td>
2,141
</td>
<td>
2.688
</td>
<td>
1.175
</td>
<td>
1.000
</td>
<td>
2.000
</td>
<td>
4.000
</td>
<td>
5.000
</td>
</tr>
<tr>
<td style="text-align:left">
pref_netw
</td>
<td>
2,141
</td>
<td>
2.408
</td>
<td>
1.106
</td>
<td>
1.000
</td>
<td>
2.000
</td>
<td>
3.000
</td>
<td>
5.000
</td>
</tr>
<tr>
<td colspan="8" style="border-bottom: 1px solid black">
</td>
</tr>
</table>
<pre class="r"><code>cor04&lt;-polychoric(select(dat04,perc_effort,perc_talent,perc_wpart,perc_netw,pref_effort,pref_talent,pref_wpart,pref_netw))
corrplot(cor04$rho, method=&quot;color&quot;,type = &quot;upper&quot;, order = &quot;hclust&quot;, tl.col = &quot;black&quot;, tl.srt = 45,addCoef.col = &quot;black&quot;,diag = FALSE)</code></pre>
<p><img src="prod_analysis-cfa_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<pre class="r"><code>model04 &lt;- &#39;
perc_merit =~ perc_effort+perc_talent 
perc_nmerit=~perc_wpart +perc_netw  
pref_merit =~ pref_effort+pref_talent 
pref_nmerit=~pref_wpart +pref_netw&#39;

fit4_c &lt;- cfa(model = model04,data = dat04,estimator=&quot;MLR&quot;,std.lv=FALSE) # Continuo/ estimador ML Robust

fit4_o &lt;- cfa(model = model04,data = dat04,ordered = c(&quot;perc_effort&quot;,&quot;perc_talent&quot;,
                                                       &quot;perc_wpart&quot;,&quot;perc_netw&quot;,
                                                       &quot;pref_effort&quot;,&quot;pref_talent&quot;,
                                                       &quot;pref_wpart&quot;,&quot;pref_netw&quot;),std.lv=FALSE)
#---------------------------------------------------#
#summary(fit4_c,standardized=TRUE, fit.measures=TRUE)
fitmeasures(fit4_c)[c(&quot;chisq.scaled&quot;,&quot;df&quot;,&quot;cfi&quot;,&quot;cfi.scaled&quot;,&quot;cfi.robust&quot;,&quot;rmsea&quot;,&quot;rmsea.scaled&quot;,&quot;rmsea.robust&quot;)]
semPlot::semPaths(object = fit3_c,what = &quot;std&quot;,thresholds = FALSE, intercepts = FALSE,fade=FALSE,curve = 2)</code></pre>
<p><img src="prod_analysis-cfa_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<pre class="r"><code>#summary(fit4_o,standardized=TRUE, fit.measures=TRUE)
fitmeasures(fit4_o)[c(&quot;chisq.scaled&quot;,&quot;df&quot;,&quot;cfi&quot;,&quot;cfi.scaled&quot;,&quot;cfi.robust&quot;,&quot;rmsea&quot;,&quot;rmsea.scaled&quot;,&quot;rmsea.robust&quot;)]
semPlot::semPaths(object = fit3_o,what = &quot;std&quot;,thresholds = FALSE, intercepts = FALSE,fade=FALSE,curve = 2)</code></pre>
<p><img src="prod_analysis-cfa_files/figure-html/unnamed-chunk-17-2.png" width="672" /></p>
<pre><code>## chisq.scaled           df          cfi   cfi.scaled   cfi.robust        rmsea rmsea.scaled 
## 181.10487966  14.00000000   0.95270053   0.94250163   0.95276313   0.07634040   0.07466588 
## rmsea.robust 
##   0.07621226 
## chisq.scaled           df          cfi   cfi.scaled   cfi.robust        rmsea rmsea.scaled 
## 200.77235322  14.00000000   0.99018169   0.97680332           NA   0.05987601   0.07895605 
## rmsea.robust 
##           NA</code></pre>
<div id="resumen-ajuste-ola-01" class="section level3" number="2.4.1">
<h3 number="2.4.1"><span class="header-section-number">2.4.1</span> Resumen ajuste ola 01</h3>
<pre class="r"><code>sum_fit&lt;- bind_rows(fitmeasures(fit1_c)[c(&quot;chisq.scaled&quot;,&quot;df&quot;,&quot;cfi&quot;,&quot;cfi.scaled&quot;,&quot;cfi.robust&quot;,&quot;rmsea&quot;,&quot;rmsea.scaled&quot;,&quot;rmsea.robust&quot;)],
                    fitmeasures(fit1_o)[c(&quot;chisq.scaled&quot;,&quot;df&quot;,&quot;cfi&quot;,&quot;cfi.scaled&quot;,&quot;cfi.robust&quot;,&quot;rmsea&quot;,&quot;rmsea.scaled&quot;,&quot;rmsea.robust&quot;)],
                    fitmeasures(fit2_c)[c(&quot;chisq.scaled&quot;,&quot;df&quot;,&quot;cfi&quot;,&quot;cfi.scaled&quot;,&quot;cfi.robust&quot;,&quot;rmsea&quot;,&quot;rmsea.scaled&quot;,&quot;rmsea.robust&quot;)],
                    fitmeasures(fit2_o)[c(&quot;chisq.scaled&quot;,&quot;df&quot;,&quot;cfi&quot;,&quot;cfi.scaled&quot;,&quot;cfi.robust&quot;,&quot;rmsea&quot;,&quot;rmsea.scaled&quot;,&quot;rmsea.robust&quot;)],
                    fitmeasures(fit3_c)[c(&quot;chisq.scaled&quot;,&quot;df&quot;,&quot;cfi&quot;,&quot;cfi.scaled&quot;,&quot;cfi.robust&quot;,&quot;rmsea&quot;,&quot;rmsea.scaled&quot;,&quot;rmsea.robust&quot;)],
                    fitmeasures(fit3_o)[c(&quot;chisq.scaled&quot;,&quot;df&quot;,&quot;cfi&quot;,&quot;cfi.scaled&quot;,&quot;cfi.robust&quot;,&quot;rmsea&quot;,&quot;rmsea.scaled&quot;,&quot;rmsea.robust&quot;)],
                    fitmeasures(fit4_c)[c(&quot;chisq.scaled&quot;,&quot;df&quot;,&quot;cfi&quot;,&quot;cfi.scaled&quot;,&quot;cfi.robust&quot;,&quot;rmsea&quot;,&quot;rmsea.scaled&quot;,&quot;rmsea.robust&quot;)],
                    fitmeasures(fit4_o)[c(&quot;chisq.scaled&quot;,&quot;df&quot;,&quot;cfi&quot;,&quot;cfi.scaled&quot;,&quot;cfi.robust&quot;,&quot;rmsea&quot;,&quot;rmsea.scaled&quot;,&quot;rmsea.robust&quot;)])
sum_fit$mod &lt;- c(&quot;Modelo 1&quot;,&quot;Modelo 1&quot;,&quot;Modelo 2&quot;,&quot;Modelo 2&quot;,&quot;Modelo 3&quot;,&quot;Modelo 3&quot;,&quot;Modelo 4&quot;,&quot;Modelo 4&quot;)
sum_fit$est &lt;- c(&quot;Continuo&quot;,&quot;Ordinal&quot;,&quot;Continuo&quot;,&quot;Ordinal&quot;,&quot;Continuo&quot;,&quot;Ordinal&quot;,&quot;Continuo&quot;,&quot;Ordinal&quot;)
sum_fit &lt;- select(sum_fit,mod,est,everything())

kable(sum_fit,digits = 3,format = &quot;html&quot;,row.names = F,booktabs=T, caption = &quot;Resumen estadísticos de ajuste ola 1&quot;) %&gt;% kable_styling(full_width = F) %&gt;% 
  collapse_rows(columns = 1,valign = &quot;middle&quot;)  %&gt;% 
  footnote(number = c(&quot;Modelo 1: fixed order by percepction/preference&quot;, 
                      &quot;Modelo 2: fixed order by topic (i.e: effort)&quot;, 
                      &quot;Modelo 3: Randomized order&quot;,
                      &quot;Modelo 4: Complete sample&quot;))</code></pre>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
Resumen estadísticos de ajuste ola 1
</caption>
<thead>
<tr>
<th style="text-align:left;">
mod
</th>
<th style="text-align:left;">
est
</th>
<th style="text-align:right;">
chisq.scaled
</th>
<th style="text-align:right;">
df
</th>
<th style="text-align:right;">
cfi
</th>
<th style="text-align:right;">
cfi.scaled
</th>
<th style="text-align:right;">
cfi.robust
</th>
<th style="text-align:right;">
rmsea
</th>
<th style="text-align:right;">
rmsea.scaled
</th>
<th style="text-align:right;">
rmsea.robust
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;vertical-align: middle !important;" rowspan="2">
Modelo 1
</td>
<td style="text-align:left;">
Continuo
</td>
<td style="text-align:right;">
42.935
</td>
<td style="text-align:right;">
14
</td>
<td style="text-align:right;">
0.979
</td>
<td style="text-align:right;">
0.977
</td>
<td style="text-align:right;">
0.980
</td>
<td style="text-align:right;">
0.058
</td>
<td style="text-align:right;">
0.054
</td>
<td style="text-align:right;">
0.057
</td>
</tr>
<tr>
<td style="text-align:left;">
Ordinal
</td>
<td style="text-align:right;">
46.114
</td>
<td style="text-align:right;">
14
</td>
<td style="text-align:right;">
0.998
</td>
<td style="text-align:right;">
0.992
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
0.038
</td>
<td style="text-align:right;">
0.057
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:left;vertical-align: middle !important;" rowspan="2">
Modelo 2
</td>
<td style="text-align:left;">
Continuo
</td>
<td style="text-align:right;">
100.062
</td>
<td style="text-align:right;">
14
</td>
<td style="text-align:right;">
0.926
</td>
<td style="text-align:right;">
0.912
</td>
<td style="text-align:right;">
0.926
</td>
<td style="text-align:right;">
0.096
</td>
<td style="text-align:right;">
0.093
</td>
<td style="text-align:right;">
0.095
</td>
</tr>
<tr>
<td style="text-align:left;">
Ordinal
</td>
<td style="text-align:right;">
101.482
</td>
<td style="text-align:right;">
14
</td>
<td style="text-align:right;">
0.984
</td>
<td style="text-align:right;">
0.962
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
0.071
</td>
<td style="text-align:right;">
0.094
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:left;vertical-align: middle !important;" rowspan="2">
Modelo 3
</td>
<td style="text-align:left;">
Continuo
</td>
<td style="text-align:right;">
57.058
</td>
<td style="text-align:right;">
14
</td>
<td style="text-align:right;">
0.952
</td>
<td style="text-align:right;">
0.942
</td>
<td style="text-align:right;">
0.952
</td>
<td style="text-align:right;">
0.069
</td>
<td style="text-align:right;">
0.066
</td>
<td style="text-align:right;">
0.068
</td>
</tr>
<tr>
<td style="text-align:left;">
Ordinal
</td>
<td style="text-align:right;">
60.025
</td>
<td style="text-align:right;">
14
</td>
<td style="text-align:right;">
0.992
</td>
<td style="text-align:right;">
0.980
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
0.051
</td>
<td style="text-align:right;">
0.069
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:left;vertical-align: middle !important;" rowspan="2">
Modelo 4
</td>
<td style="text-align:left;">
Continuo
</td>
<td style="text-align:right;">
181.105
</td>
<td style="text-align:right;">
14
</td>
<td style="text-align:right;">
0.953
</td>
<td style="text-align:right;">
0.943
</td>
<td style="text-align:right;">
0.953
</td>
<td style="text-align:right;">
0.076
</td>
<td style="text-align:right;">
0.075
</td>
<td style="text-align:right;">
0.076
</td>
</tr>
<tr>
<td style="text-align:left;">
Ordinal
</td>
<td style="text-align:right;">
200.772
</td>
<td style="text-align:right;">
14
</td>
<td style="text-align:right;">
0.990
</td>
<td style="text-align:right;">
0.977
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
0.060
</td>
<td style="text-align:right;">
0.079
</td>
<td style="text-align:right;">
</td>
</tr>
</tbody>
<tfoot>
<tr>
<td style="padding: 0; border: 0;" colspan="100%">
<sup>1</sup> Modelo 1: fixed order by percepction/preference
</td>
</tr>
<tr>
<td style="padding: 0; border: 0;" colspan="100%">
<sup>2</sup> Modelo 2: fixed order by topic (i.e: effort)
</td>
</tr>
<tr>
<td style="padding: 0; border: 0;" colspan="100%">
<sup>3</sup> Modelo 3: Randomized order
</td>
</tr>
<tr>
<td style="padding: 0; border: 0;" colspan="100%">
<sup>4</sup> Modelo 4: Complete sample
</td>
</tr>
</tfoot>
</table>
</div>
</div>
<div id="análisis-por-grupos-múltiples" class="section level2" number="2.5">
<h2 number="2.5"><span class="header-section-number">2.5</span> Análisis por Grupos múltiples</h2>
<pre class="r"><code>model04 &lt;- &#39;
perc_merit =~ perc_effort+perc_talent 
perc_nmerit=~perc_wpart +perc_netw  
pref_merit =~ pref_effort+pref_talent 
pref_nmerit=~pref_wpart +pref_netw&#39;

fit4_c_mg &lt;- cfa(model = model04,data = dat04,estimator=&quot;MLR&quot;,std.lv=FALSE,group = &quot;grupo&quot;) # Continuo/ estimador ML Robust

fit4_o_mg &lt;- cfa(model = model04,data = dat04,ordered = c(&quot;perc_effort&quot;,&quot;perc_talent&quot;,
                                                       &quot;perc_wpart&quot;,&quot;perc_netw&quot;,
                                                       &quot;pref_effort&quot;,&quot;pref_talent&quot;,
                                                       &quot;pref_wpart&quot;,&quot;pref_netw&quot;),std.lv=FALSE, group = &quot;grupo&quot;)
#---------------------------------------------------#
#summary(fit4_c_mg,standardized=TRUE, fit.measures=TRUE)
fitmeasures(fit4_c_mg)[c(&quot;cfi&quot;,&quot;cfi.scaled&quot;,&quot;cfi.robust&quot;,&quot;rmsea&quot;,&quot;rmsea.scaled&quot;,&quot;rmsea.robust&quot;)]
semPlot::semPaths(object = fit4_c_mg,what = &quot;std&quot;,thresholds = FALSE, intercepts = FALSE, fade=FALSE, curve=2)</code></pre>
<p><img src="prod_analysis-cfa_files/figure-html/unnamed-chunk-19-1.png" width="672" /><img src="prod_analysis-cfa_files/figure-html/unnamed-chunk-19-2.png" width="672" /><img src="prod_analysis-cfa_files/figure-html/unnamed-chunk-19-3.png" width="672" /></p>
<pre class="r"><code>#summary(fit4_o_mg,standardized=TRUE, fit.measures=TRUE)
fitmeasures(fit4_o_mg)[c(&quot;cfi&quot;,&quot;cfi.scaled&quot;,&quot;cfi.robust&quot;,&quot;rmsea&quot;,&quot;rmsea.scaled&quot;,&quot;rmsea.robust&quot;)]
semPlot::semPaths(object = fit4_o_mg,what = &quot;std&quot;,thresholds = FALSE, intercepts = FALSE,fade=FALSE, curve=2)</code></pre>
<p><img src="prod_analysis-cfa_files/figure-html/unnamed-chunk-19-4.png" width="672" /><img src="prod_analysis-cfa_files/figure-html/unnamed-chunk-19-5.png" width="672" /><img src="prod_analysis-cfa_files/figure-html/unnamed-chunk-19-6.png" width="672" /></p>
<pre><code>##          cfi   cfi.scaled   cfi.robust        rmsea rmsea.scaled rmsea.robust 
##   0.95494030   0.94697921   0.95532301   0.07575741   0.07314653   0.07522301 
##          cfi   cfi.scaled   cfi.robust        rmsea rmsea.scaled rmsea.robust 
##   0.99236975   0.98072106           NA   0.05571542   0.07542086           NA</code></pre>
<p>Cosas por probar:</p>
<ul>
<li>V01+V02: cargas y fit</li>
<li>V01+V03: cargas y fit</li>
<li>V02+V03: cargas y fit</li>
</ul>
</div>
</div>
<div id="modelo-factorial-de-segundo-orden" class="section level1" number="3">
<h1 number="3"><span class="header-section-number">3</span> Modelo Factorial de Segundo Orden:</h1>
<div id="a.-factor-de-segundo-orden-por-percepción-y-preferencia" class="section level2" number="3.1">
<h2 number="3.1"><span class="header-section-number">3.1</span> a. Factor de segundo orden por Percepción y Preferencia</h2>
<pre class="r"><code>model04b1or &lt;- &#39;
perc_merit=~ perc_effort+perc_talent 
perc_nmerit=~perc_wpart +perc_netw  
pref_merit=~ pref_effort+pref_talent 
pref_nmerit=~pref_wpart +pref_netw
percep=~ perc_merit + perc_nmerit
prefer=~ pref_merit + pref_nmerit&#39;

fit4a_c &lt;- cfa(model = model04b1or,data = dat04, estimator=&quot;MLR&quot;)

fit4b_c &lt;- cfa(model = model04b1or,data = dat04,ordered = c(&quot;perc_effort&quot;,&quot;perc_talent&quot;,&quot;perc_wpart&quot;,&quot;perc_netw&quot;,
                                                            &quot;pref_effort&quot;,&quot;pref_talent&quot;,&quot;pref_wpart&quot;,&quot;pref_netw&quot;))

#---------------------------------------------------#
#summary(fit4a_c,standardized=TRUE, fit.measures=TRUE)
fitmeasures(fit4a_c)[c(&quot;cfi&quot;,&quot;cfi.scaled&quot;,&quot;cfi.robust&quot;,&quot;rmsea&quot;,&quot;rmsea.scaled&quot;,&quot;rmsea.robust&quot;)]
semPlot::semPaths(object = fit4a_c,what = &quot;std&quot;,thresholds = FALSE, intercepts = FALSE, fade=FALSE,curve=2)</code></pre>
<p><img src="prod_analysis-cfa_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<pre class="r"><code>#summary(fit4b_c,standardized=TRUE, fit.measures=TRUE)
fitmeasures(fit4b_c)[c(&quot;cfi&quot;,&quot;cfi.scaled&quot;,&quot;cfi.robust&quot;,&quot;rmsea&quot;,&quot;rmsea.scaled&quot;,&quot;rmsea.robust&quot;)]
semPlot::semPaths(object = fit4b_c,what = &quot;std&quot;,thresholds = FALSE, intercepts = FALSE, fade=FALSE,curve=2)</code></pre>
<p><img src="prod_analysis-cfa_files/figure-html/unnamed-chunk-20-2.png" width="672" /></p>
<pre><code>##          cfi   cfi.scaled   cfi.robust        rmsea rmsea.scaled rmsea.robust 
##   0.94736842   0.93880041   0.94760970   0.07779789   0.07441956   0.07754042 
##          cfi   cfi.scaled   cfi.robust        rmsea rmsea.scaled rmsea.robust 
##   0.98259229   0.97082290           NA   0.07702357   0.08554841           NA</code></pre>
<blockquote>
<p><strong>NOTA:</strong> Cargas factoriales de segundo orden son bajas. El ajuste del modelo no es bueno.</p>
</blockquote>
</div>
<div id="b.-factor-de-segundo-orden-por-meritocracia-y-no-meritocracia" class="section level2" number="3.2">
<h2 number="3.2"><span class="header-section-number">3.2</span> b. Factor de segundo orden por Meritocracia y No Meritocracia</h2>
<pre class="r"><code>model04b2or &lt;-&#39;perc_merit=~ perc_effort+perc_talent
               perc_nmerit=~perc_wpart +perc_netw
               pref_merit=~ pref_effort+pref_talent
               pref_nmerit=~pref_wpart +pref_netw
               merit =~ perc_merit  + pref_merit
               nmerit=~ perc_nmerit + pref_nmerit&#39;

# fit4b_c &lt;- cfa(model = model04b2or,data = dat04,estimator=&quot;MLR&quot;) # No converge

fit4b_o &lt;- cfa(model = model04b2or,data = dat04, 
               ordered = c(&quot;perc_effort&quot;,&quot;perc_talent&quot;,&quot;perc_wpart&quot;,&quot;perc_netw&quot;,
                           &quot;pref_effort&quot;,&quot;pref_talent&quot;,&quot;pref_wpart&quot;,&quot;pref_netw&quot;))

#---------------------------------------------------#
# #summary(fit4b_c,standardized=TRUE, fit.measures=TRUE)
# fitmeasures(fit4b_c)[c(&quot;cfi&quot;,&quot;cfi.scaled&quot;,&quot;cfi.robust&quot;,&quot;rmsea&quot;,&quot;rmsea.scaled&quot;,&quot;rmsea.robust&quot;)]
# semPlot::semPaths(object = fit4b_c,what = &quot;std&quot;,thresholds = FALSE, intercepts = FALSE, fade=FALSE, curve=2)

#summary(fit4b_o,standardized=TRUE, fit.measures=TRUE)
fitmeasures(fit4b_o)[c(&quot;cfi&quot;,&quot;cfi.scaled&quot;,&quot;cfi.robust&quot;,&quot;rmsea&quot;,&quot;rmsea.scaled&quot;,&quot;rmsea.robust&quot;)]
semPlot::semPaths(object = fit4b_o,what = &quot;std&quot;,thresholds = FALSE, intercepts = FALSE, fade=FALSE, curve=2)</code></pre>
<p><img src="prod_analysis-cfa_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<pre><code>##          cfi   cfi.scaled   cfi.robust        rmsea rmsea.scaled rmsea.robust 
##   0.97583700   0.95699375           NA   0.09074615   0.10386199           NA</code></pre>
<blockquote>
<p><strong>NOTA:</strong> El modelo estimado con MLR con factores de segundo orden “meritocracia/ no meritocracia” no converge. EL modelo estimado a través de DWLS converge, posee cargas muy bajas y una muy alta (merit~pref_merit). Fit es malo (RMSEA &gt;.10)</p>
</blockquote>
</div>
</div>
<div id="wave-02" class="section level1" number="4">
<h1 number="4"><span class="header-section-number">4</span> Wave 02</h1>
<pre class="r"><code>data02 &lt;- sjlabelled::read_spss(path = &quot;input/data/original/Estudio_3_ola2.sav&quot;,verbose = FALSE)
load(file = &quot;input/data/proc/datawide.RData&quot;)
dat01 &lt;- data02 %&gt;% select(starts_with(&quot;meritv03_p&quot;)) </code></pre>
<div id="ate-indicadores-meritocracia" class="section level2" number="4.1">
<h2 number="4.1"><span class="header-section-number">4.1</span> ATE indicadores meritocracia</h2>
<pre class="r"><code>m01&lt;- lm(perc_effort_w2~treat,data = wide01)
m02&lt;- lm(perc_talent_w2~treat,data = wide01)
m03&lt;- lm(perc_wpart_w2~treat, data = wide01)
m04&lt;- lm(perc_netw_w2~treat,  data = wide01)
#--------------------------------------------#
m05&lt;- lm(pref_effort_w2~treat,data = wide01)
m06&lt;- lm(pref_talent_w2~treat,data = wide01)
m07&lt;- lm(pref_wpart_w2 ~treat, data = wide01)
m08&lt;- lm(pref_netw_w2  ~treat,  data = wide01)
#--------------------------------------------#
stargazer::stargazer(m01,m02,m03,m04,type = &quot;html&quot;)</code></pre>
<table style="text-align:center">
<tr>
<td colspan="5" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td colspan="4">
<em>Dependent variable:</em>
</td>
</tr>
<tr>
<td>
</td>
<td colspan="4" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
perc_effort_w2
</td>
<td>
perc_talent_w2
</td>
<td>
perc_wpart_w2
</td>
<td>
perc_netw_w2
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(1)
</td>
<td>
(2)
</td>
<td>
(3)
</td>
<td>
(4)
</td>
</tr>
<tr>
<td colspan="5" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
treatpobreza
</td>
<td>
0.061
</td>
<td>
-0.018
</td>
<td>
-0.047
</td>
<td>
-0.010
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.072)
</td>
<td>
(0.064)
</td>
<td>
(0.077)
</td>
<td>
(0.073)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
treatdesiguald
</td>
<td>
-0.078
</td>
<td>
-0.092
</td>
<td>
0.057
</td>
<td>
0.020
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.072)
</td>
<td>
(0.063)
</td>
<td>
(0.077)
</td>
<td>
(0.072)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
Constant
</td>
<td>
3.322<sup>***</sup>
</td>
<td>
3.164<sup>***</sup>
</td>
<td>
3.542<sup>***</sup>
</td>
<td>
3.547<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.051)
</td>
<td>
(0.045)
</td>
<td>
(0.054)
</td>
<td>
(0.051)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td colspan="5" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
Observations
</td>
<td>
1,777
</td>
<td>
1,777
</td>
<td>
1,777
</td>
<td>
1,777
</td>
</tr>
<tr>
<td style="text-align:left">
R<sup>2</sup>
</td>
<td>
0.002
</td>
<td>
0.001
</td>
<td>
0.001
</td>
<td>
0.0001
</td>
</tr>
<tr>
<td style="text-align:left">
Adjusted R<sup>2</sup>
</td>
<td>
0.001
</td>
<td>
0.0002
</td>
<td>
-0.0001
</td>
<td>
-0.001
</td>
</tr>
<tr>
<td style="text-align:left">
Residual Std. Error (df = 1774)
</td>
<td>
1.239
</td>
<td>
1.094
</td>
<td>
1.326
</td>
<td>
1.249
</td>
</tr>
<tr>
<td style="text-align:left">
F Statistic (df = 2; 1774)
</td>
<td>
1.844
</td>
<td>
1.175
</td>
<td>
0.907
</td>
<td>
0.084
</td>
</tr>
<tr>
<td colspan="5" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
<em>Note:</em>
</td>
<td colspan="4" style="text-align:right">
<sup><em></sup>p&lt;0.1; <sup><strong></sup>p&lt;0.05; <sup></strong></em></sup>p&lt;0.01
</td>
</tr>
</table>
<pre class="r"><code>stargazer::stargazer(m05,m06,m07,m08,type = &quot;html&quot;)</code></pre>
<table style="text-align:center">
<tr>
<td colspan="5" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td colspan="4">
<em>Dependent variable:</em>
</td>
</tr>
<tr>
<td>
</td>
<td colspan="4" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
pref_effort_w2
</td>
<td>
pref_talent_w2
</td>
<td>
pref_wpart_w2
</td>
<td>
pref_netw_w2
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(1)
</td>
<td>
(2)
</td>
<td>
(3)
</td>
<td>
(4)
</td>
</tr>
<tr>
<td colspan="5" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
treatpobreza
</td>
<td>
0.085
</td>
<td>
0.064
</td>
<td>
0.059
</td>
<td>
-0.094
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.067)
</td>
<td>
(0.066)
</td>
<td>
(0.067)
</td>
<td>
(0.062)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
treatdesiguald
</td>
<td>
0.058
</td>
<td>
0.043
</td>
<td>
-0.017
</td>
<td>
-0.101
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.067)
</td>
<td>
(0.065)
</td>
<td>
(0.067)
</td>
<td>
(0.062)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
Constant
</td>
<td>
3.879<sup>***</sup>
</td>
<td>
3.237<sup>***</sup>
</td>
<td>
2.592<sup>***</sup>
</td>
<td>
2.374<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.047)
</td>
<td>
(0.046)
</td>
<td>
(0.047)
</td>
<td>
(0.044)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td colspan="5" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
Observations
</td>
<td>
1,777
</td>
<td>
1,777
</td>
<td>
1,777
</td>
<td>
1,777
</td>
</tr>
<tr>
<td style="text-align:left">
R<sup>2</sup>
</td>
<td>
0.001
</td>
<td>
0.001
</td>
<td>
0.001
</td>
<td>
0.002
</td>
</tr>
<tr>
<td style="text-align:left">
Adjusted R<sup>2</sup>
</td>
<td>
-0.0002
</td>
<td>
-0.001
</td>
<td>
-0.0003
</td>
<td>
0.001
</td>
</tr>
<tr>
<td style="text-align:left">
Residual Std. Error (df = 1774)
</td>
<td>
1.155
</td>
<td>
1.128
</td>
<td>
1.154
</td>
<td>
1.065
</td>
</tr>
<tr>
<td style="text-align:left">
F Statistic (df = 2; 1774)
</td>
<td>
0.841
</td>
<td>
0.503
</td>
<td>
0.709
</td>
<td>
1.660
</td>
</tr>
<tr>
<td colspan="5" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
<em>Note:</em>
</td>
<td colspan="4" style="text-align:right">
<sup><em></sup>p&lt;0.1; <sup><strong></sup>p&lt;0.05; <sup></strong></em></sup>p&lt;0.01
</td>
</tr>
</table>
<blockquote>
<p><strong>NOTA</strong>: Los tratamientos de información no se asocian de manera estadísticamente significativa con ninguno de los indicadores de la escala de meritocracia.</p>
</blockquote>
</div>
<div id="cfa-muestra-completa-control-desigualdad-y-pobreza" class="section level2" number="4.2">
<h2 number="4.2"><span class="header-section-number">4.2</span> CFA Muestra completa (Control, Desigualdad y Pobreza)</h2>
<table style="text-align:center">
<tr>
<td colspan="8" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
Statistic
</td>
<td>
N
</td>
<td>
Mean
</td>
<td>
St. Dev.
</td>
<td>
Min
</td>
<td>
Pctl(25)
</td>
<td>
Pctl(75)
</td>
<td>
Max
</td>
</tr>
<tr>
<td colspan="8" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
meritv03_perc_effort
</td>
<td>
1,772
</td>
<td>
3.318
</td>
<td>
1.240
</td>
<td>
1.000
</td>
<td>
2.000
</td>
<td>
4.000
</td>
<td>
5.000
</td>
</tr>
<tr>
<td style="text-align:left">
meritv03_perc_talent
</td>
<td>
1,772
</td>
<td>
3.125
</td>
<td>
1.095
</td>
<td>
1.000
</td>
<td>
2.000
</td>
<td>
4.000
</td>
<td>
5.000
</td>
</tr>
<tr>
<td style="text-align:left">
meritv03_perc_wpart
</td>
<td>
1,772
</td>
<td>
3.547
</td>
<td>
1.325
</td>
<td>
1.000
</td>
<td>
3.000
</td>
<td>
5.000
</td>
<td>
5.000
</td>
</tr>
<tr>
<td style="text-align:left">
meritv03_perc_netw
</td>
<td>
1,772
</td>
<td>
3.549
</td>
<td>
1.249
</td>
<td>
1.000
</td>
<td>
3.000
</td>
<td>
4.000
</td>
<td>
5.000
</td>
</tr>
<tr>
<td style="text-align:left">
meritv03_pref_effort
</td>
<td>
1,772
</td>
<td>
3.924
</td>
<td>
1.157
</td>
<td>
1.000
</td>
<td>
3.000
</td>
<td>
5.000
</td>
<td>
5.000
</td>
</tr>
<tr>
<td style="text-align:left">
meritv03_pref_talent
</td>
<td>
1,772
</td>
<td>
3.274
</td>
<td>
1.128
</td>
<td>
1.000
</td>
<td>
3.000
</td>
<td>
4.000
</td>
<td>
5.000
</td>
</tr>
<tr>
<td style="text-align:left">
meritv03_pref_wpart
</td>
<td>
1,772
</td>
<td>
2.607
</td>
<td>
1.154
</td>
<td>
1.000
</td>
<td>
2.000
</td>
<td>
3.000
</td>
<td>
5.000
</td>
</tr>
<tr>
<td style="text-align:left">
meritv03_pref_netw
</td>
<td>
1,772
</td>
<td>
2.308
</td>
<td>
1.065
</td>
<td>
1.000
</td>
<td>
1.000
</td>
<td>
3.000
</td>
<td>
5.000
</td>
</tr>
<tr>
<td colspan="8" style="border-bottom: 1px solid black">
</td>
</tr>
</table>
<pre class="r"><code>dat01cor&lt;- select(dat01,meritv03_perc_effort,meritv03_perc_talent,
                        meritv03_perc_wpart,meritv03_perc_netw,
                        meritv03_pref_effort,meritv03_pref_talent,
                        meritv03_pref_wpart,meritv03_pref_netw)
cor01&lt;-polychoric(dat01cor)
corrplot(cor01$rho, type = &quot;upper&quot;, tl.col = &quot;black&quot;, tl.srt = 45,addCoef.col = &quot;black&quot;,diag = FALSE)</code></pre>
<p><img src="prod_analysis-cfa_files/figure-html/unnamed-chunk-25-1.png" width="672" /></p>
<pre class="r"><code>model03 &lt;- &#39;
perc_merit=~meritv03_perc_effort+meritv03_perc_talent 
perc_nmerit=~meritv03_perc_wpart+meritv03_perc_netw  
pref_merit=~meritv03_pref_effort+meritv03_pref_talent 
pref_nmerit=~meritv03_pref_wpart+meritv03_pref_netw&#39;

fitw02_c &lt;- cfa(model = model03,data = dat01,estimator=&quot;MLR&quot;,std.lv=FALSE) # Continuo/ estimador ML Robust

fitw02_o &lt;- cfa(model = model03,data = dat01,ordered = c(&quot;meritv03_perc_effort&quot;,&quot;meritv03_perc_talent&quot;,
                                                          &quot;meritv03_perc_wpart&quot;,&quot;meritv03_perc_netw&quot;,
                                                          &quot;meritv03_pref_effort&quot;,&quot;meritv03_pref_talent&quot;,
                                                          &quot;meritv03_pref_wpart&quot;,&quot;meritv03_pref_netw&quot;))
#---------------------------------------------------#
#summary(fitw02_c,standardized=TRUE, fit.measures=TRUE)
fitmeasures(fitw02_c)[c(&quot;cfi&quot;,&quot;cfi.scaled&quot;,&quot;cfi.robust&quot;,&quot;rmsea&quot;,&quot;rmsea.scaled&quot;,&quot;rmsea.robust&quot;)]
semPlot::semPaths(object = fitw02_c,what = &quot;std&quot;,thresholds = FALSE, intercepts = FALSE,fade=FALSE,curve=2)</code></pre>
<p><img src="prod_analysis-cfa_files/figure-html/unnamed-chunk-26-1.png" width="672" /></p>
<pre class="r"><code>#summary(fitw02_o,standardized=TRUE, fit.measures=TRUE)
fitmeasures(fitw02_o)[c(&quot;cfi&quot;,&quot;cfi.scaled&quot;,&quot;cfi.robust&quot;,&quot;rmsea&quot;,&quot;rmsea.scaled&quot;,&quot;rmsea.robust&quot;)]
semPlot::semPaths(object = fitw02_o,what = &quot;std&quot;,thresholds = FALSE, intercepts = FALSE,fade=FALSE,curve=2)</code></pre>
<p><img src="prod_analysis-cfa_files/figure-html/unnamed-chunk-26-2.png" width="672" /></p>
<pre><code>##          cfi   cfi.scaled   cfi.robust        rmsea rmsea.scaled rmsea.robust 
##   0.96683191   0.96480728   0.96795005   0.05064198   0.04589567   0.04967688 
##          cfi   cfi.scaled   cfi.robust        rmsea rmsea.scaled rmsea.robust 
##   0.98784345   0.97481090           NA   0.04672993   0.05956625           NA</code></pre>
<blockquote>
<p><strong>NOTA</strong>: El ajuste de muestra completa en wave 02 con estimador MLR (robusto) es bastante bueno (CFI, RMSEA). El ajuste con DWLS es bastante bueno, CFI mejora, RMSEA aumenta un poco (0.59).</p>
</blockquote>
<ul>
<li><strong>Recomendación</strong>: es probable que el estimador MLR sea mejor que el ordinal.</li>
</ul>
<div id="factor-de-segundo-orden" class="section level3" number="4.2.1">
<h3 number="4.2.1"><span class="header-section-number">4.2.1</span> Factor de segundo orden</h3>
<pre class="r"><code>modw2 &lt;- &#39;
perc_merit=~meritv03_perc_effort+meritv03_perc_talent 
perc_nmerit=~meritv03_perc_wpart+meritv03_perc_netw  
pref_merit=~meritv03_pref_effort+meritv03_pref_talent 
pref_nmerit=~meritv03_pref_wpart+meritv03_pref_netw 
merit =~perc_merit+pref_merit  
nmerit=~perc_nmerit+pref_nmerit&#39;

# mod2_merit_c &lt;- cfa(model = modw2,data = dat01) # Continuo/ estimador ML Robust

mod2_merit_o &lt;- cfa(model = modw2,data = dat01,ordered = c(&quot;meritv03_perc_effort&quot;,&quot;meritv03_perc_talent&quot;,
                                                           &quot;meritv03_perc_wpart&quot;,&quot;meritv03_perc_netw&quot;,
                                                           &quot;meritv03_pref_effort&quot;,&quot;meritv03_pref_talent&quot;,
                                                           &quot;meritv03_pref_wpart&quot;,&quot;meritv03_pref_netw&quot;))

#---------------------------------------------------#
# #summary(mod2_merit_c,standardized=TRUE, fit.measures=TRUE)
# fitmeasures(mod2_merit_c)[c(&quot;cfi&quot;,&quot;cfi.scaled&quot;,&quot;cfi.robust&quot;,&quot;rmsea&quot;,&quot;rmsea.scaled&quot;,&quot;rmsea.robust&quot;)]
# semPlot::semPaths(object = mod2_merit_c,what = &quot;std&quot;,thresholds = FALSE, intercepts = FALSE)

#summary(mod2_merit_o,standardized=TRUE, fit.measures=TRUE)
fitmeasures(mod2_merit_o)[c(&quot;cfi&quot;,&quot;cfi.scaled&quot;,&quot;cfi.robust&quot;,&quot;rmsea&quot;,&quot;rmsea.scaled&quot;,&quot;rmsea.robust&quot;)]
semPlot::semPaths(object = mod2_merit_o,what = &quot;std&quot;,thresholds = FALSE, intercepts = FALSE,fade=FALSE, curve=2, rotation=2)</code></pre>
<p><img src="prod_analysis-cfa_files/figure-html/unnamed-chunk-27-1.png" width="672" /></p>
<pre><code>##          cfi   cfi.scaled   cfi.robust        rmsea rmsea.scaled rmsea.robust 
##   0.96479952   0.94371851           NA   0.07682146   0.08601914           NA</code></pre>
<blockquote>
<ul>
<li>Factor de segundo orden usando MLR no converge.</li>
<li>Factor de segundo orden usando DWLS converge, pero las cargas no son buenas y el ajuste tampoco.</li>
</ul>
</blockquote>
</div>
</div>
<div id="cfa-muestra-control" class="section level2" number="4.3">
<h2 number="4.3"><span class="header-section-number">4.3</span> CFA Muestra Control</h2>
<pre class="r"><code>w02con &lt;- data02 %&gt;% filter(FL_6_DO_Control==1) %&gt;% select(starts_with(&quot;meritv03_p&quot;)) </code></pre>
<table style="text-align:center">
<tr>
<td colspan="8" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
Statistic
</td>
<td>
N
</td>
<td>
Mean
</td>
<td>
St. Dev.
</td>
<td>
Min
</td>
<td>
Pctl(25)
</td>
<td>
Pctl(75)
</td>
<td>
Max
</td>
</tr>
<tr>
<td colspan="8" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
meritv03_perc_effort
</td>
<td>
595
</td>
<td>
3.324
</td>
<td>
1.239
</td>
<td>
1.000
</td>
<td>
2.000
</td>
<td>
4.000
</td>
<td>
5.000
</td>
</tr>
<tr>
<td style="text-align:left">
meritv03_perc_talent
</td>
<td>
595
</td>
<td>
3.165
</td>
<td>
1.087
</td>
<td>
1.000
</td>
<td>
2.000
</td>
<td>
4.000
</td>
<td>
5.000
</td>
</tr>
<tr>
<td style="text-align:left">
meritv03_perc_wpart
</td>
<td>
595
</td>
<td>
3.536
</td>
<td>
1.296
</td>
<td>
1.000
</td>
<td>
3.000
</td>
<td>
5.000
</td>
<td>
5.000
</td>
</tr>
<tr>
<td style="text-align:left">
meritv03_perc_netw
</td>
<td>
595
</td>
<td>
3.541
</td>
<td>
1.220
</td>
<td>
1.000
</td>
<td>
3.000
</td>
<td>
4.000
</td>
<td>
5.000
</td>
</tr>
<tr>
<td style="text-align:left">
meritv03_pref_effort
</td>
<td>
595
</td>
<td>
3.877
</td>
<td>
1.166
</td>
<td>
1.000
</td>
<td>
3.000
</td>
<td>
5.000
</td>
<td>
5.000
</td>
</tr>
<tr>
<td style="text-align:left">
meritv03_pref_talent
</td>
<td>
595
</td>
<td>
3.239
</td>
<td>
1.118
</td>
<td>
1.000
</td>
<td>
2.500
</td>
<td>
4.000
</td>
<td>
5.000
</td>
</tr>
<tr>
<td style="text-align:left">
meritv03_pref_wpart
</td>
<td>
595
</td>
<td>
2.588
</td>
<td>
1.147
</td>
<td>
1.000
</td>
<td>
2.000
</td>
<td>
3.000
</td>
<td>
5.000
</td>
</tr>
<tr>
<td style="text-align:left">
meritv03_pref_netw
</td>
<td>
595
</td>
<td>
2.370
</td>
<td>
1.074
</td>
<td>
1.000
</td>
<td>
2.000
</td>
<td>
3.000
</td>
<td>
5.000
</td>
</tr>
<tr>
<td colspan="8" style="border-bottom: 1px solid black">
</td>
</tr>
</table>
<pre class="r"><code>corw02_1&lt;-polychoric(w02con)
corrplot(corw02_1$rho, type = &quot;upper&quot;, order = &quot;hclust&quot;, tl.col = &quot;black&quot;, tl.srt = 45,addCoef.col = &quot;black&quot;,diag = FALSE)</code></pre>
<p><img src="prod_analysis-cfa_files/figure-html/unnamed-chunk-30-1.png" width="672" /></p>
<pre class="r"><code>model03 &lt;- &#39;
perc_merit=~meritv03_perc_effort+meritv03_perc_talent 
perc_nmerit=~meritv03_perc_wpart+meritv03_perc_netw  
pref_merit=~meritv03_pref_effort+meritv03_pref_talent 
pref_nmerit=~meritv03_pref_wpart+meritv03_pref_netw&#39;

fitw02a_c &lt;- cfa(model = model03,data = w02con,estimator=&quot;MLR&quot;) # Continuo/ estimador ML Robust

fitw02a_o &lt;- cfa(model = model03,data = w02con,ordered = c(&quot;meritv03_perc_effort&quot;,&quot;meritv03_perc_talent&quot;,
                                                           &quot;meritv03_perc_wpart&quot;,&quot;meritv03_perc_netw&quot;,
                                                           &quot;meritv03_pref_effort&quot;,&quot;meritv03_pref_talent&quot;,
                                                           &quot;meritv03_pref_wpart&quot;,&quot;meritv03_pref_netw&quot;))

#---------------------------------------------------#
#summary(fitw02a_c,standardized=TRUE, fit.measures=TRUE)
fitmeasures(fitw02a_c)[c(&quot;cfi&quot;,&quot;cfi.scaled&quot;,&quot;cfi.robust&quot;,&quot;rmsea&quot;,&quot;rmsea.scaled&quot;,&quot;rmsea.robust&quot;)]
semPlot::semPaths(object = fitw02a_c,what = &quot;std&quot;,thresholds = FALSE, intercepts = FALSE, curve=2)</code></pre>
<p><img src="prod_analysis-cfa_files/figure-html/unnamed-chunk-31-1.png" width="672" /></p>
<pre class="r"><code>#summary(fitw02a_o,standardized=TRUE, fit.measures=TRUE)
fitmeasures(fitw02a_o)[c(&quot;cfi&quot;,&quot;cfi.scaled&quot;,&quot;cfi.robust&quot;,&quot;rmsea&quot;,&quot;rmsea.scaled&quot;,&quot;rmsea.robust&quot;)]
semPlot::semPaths(object = fitw02a_o,what = &quot;std&quot;,thresholds = FALSE, intercepts = FALSE, curve=2)</code></pre>
<p><img src="prod_analysis-cfa_files/figure-html/unnamed-chunk-31-2.png" width="672" /></p>
<pre><code>##          cfi   cfi.scaled   cfi.robust        rmsea rmsea.scaled rmsea.robust 
##   0.95300796   0.95202309   0.95683934   0.05713915   0.04989786   0.05433717 
##          cfi   cfi.scaled   cfi.robust        rmsea rmsea.scaled rmsea.robust 
##   0.98848464   0.97507075           NA   0.04333340   0.05692432           NA</code></pre>
</div>
<div id="cfa-muestra-pobreza" class="section level2" number="4.4">
<h2 number="4.4"><span class="header-section-number">4.4</span> CFA Muestra Pobreza</h2>
<pre class="r"><code>w02pob &lt;- data02 %&gt;% filter(FL_6_DO_Tratamiento==1) %&gt;% select(starts_with(&quot;meritv03_p&quot;)) </code></pre>
<table style="text-align:center">
<tr>
<td colspan="8" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
Statistic
</td>
<td>
N
</td>
<td>
Mean
</td>
<td>
St. Dev.
</td>
<td>
Min
</td>
<td>
Pctl(25)
</td>
<td>
Pctl(75)
</td>
<td>
Max
</td>
</tr>
<tr>
<td colspan="8" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
meritv03_perc_effort
</td>
<td>
586
</td>
<td>
3.387
</td>
<td>
1.260
</td>
<td>
1.000
</td>
<td>
2.000
</td>
<td>
4.000
</td>
<td>
5.000
</td>
</tr>
<tr>
<td style="text-align:left">
meritv03_perc_talent
</td>
<td>
586
</td>
<td>
3.140
</td>
<td>
1.099
</td>
<td>
1.000
</td>
<td>
2.000
</td>
<td>
4.000
</td>
<td>
5.000
</td>
</tr>
<tr>
<td style="text-align:left">
meritv03_perc_wpart
</td>
<td>
586
</td>
<td>
3.493
</td>
<td>
1.368
</td>
<td>
1.000
</td>
<td>
3.000
</td>
<td>
5.000
</td>
<td>
5.000
</td>
</tr>
<tr>
<td style="text-align:left">
meritv03_perc_netw
</td>
<td>
586
</td>
<td>
3.534
</td>
<td>
1.274
</td>
<td>
1.000
</td>
<td>
3.000
</td>
<td>
4.000
</td>
<td>
5.000
</td>
</tr>
<tr>
<td style="text-align:left">
meritv03_pref_effort
</td>
<td>
586
</td>
<td>
3.956
</td>
<td>
1.173
</td>
<td>
1.000
</td>
<td>
4.000
</td>
<td>
5.000
</td>
<td>
5.000
</td>
</tr>
<tr>
<td style="text-align:left">
meritv03_pref_talent
</td>
<td>
586
</td>
<td>
3.304
</td>
<td>
1.135
</td>
<td>
1.000
</td>
<td>
3.000
</td>
<td>
4.000
</td>
<td>
5.000
</td>
</tr>
<tr>
<td style="text-align:left">
meritv03_pref_wpart
</td>
<td>
586
</td>
<td>
2.654
</td>
<td>
1.142
</td>
<td>
1.000
</td>
<td>
2.000
</td>
<td>
3.000
</td>
<td>
5.000
</td>
</tr>
<tr>
<td style="text-align:left">
meritv03_pref_netw
</td>
<td>
586
</td>
<td>
2.280
</td>
<td>
1.085
</td>
<td>
1.000
</td>
<td>
1.000
</td>
<td>
3.000
</td>
<td>
5.000
</td>
</tr>
<tr>
<td colspan="8" style="border-bottom: 1px solid black">
</td>
</tr>
</table>
<pre class="r"><code>corw02_2&lt;-polychoric(w02pob)
corrplot(corw02_2$rho, type = &quot;upper&quot;, order = &quot;hclust&quot;, tl.col = &quot;black&quot;, tl.srt = 45,addCoef.col = &quot;black&quot;,diag = FALSE)</code></pre>
<p><img src="prod_analysis-cfa_files/figure-html/unnamed-chunk-34-1.png" width="672" /></p>
<pre class="r"><code>model03 &lt;- &#39;
perc_merit=~meritv03_perc_effort+meritv03_perc_talent 
perc_nmerit=~meritv03_perc_wpart+meritv03_perc_netw  
pref_merit=~meritv03_pref_effort+meritv03_pref_talent 
pref_nmerit=~meritv03_pref_wpart+meritv03_pref_netw&#39;

fitw02b_c &lt;- cfa(model = model03,data = w02pob,estimator=&quot;MLR&quot;) # Continuo/ estimador ML Robust

fitw02b_o &lt;- cfa(model = model03,data = w02pob,ordered = c(&quot;meritv03_perc_effort&quot;,&quot;meritv03_perc_talent&quot;,
                                                     &quot;meritv03_perc_wpart&quot;,&quot;meritv03_perc_netw&quot;,
                                                     &quot;meritv03_pref_effort&quot;,&quot;meritv03_pref_talent&quot;,
                                                     &quot;meritv03_pref_wpart&quot;,&quot;meritv03_pref_netw&quot;))

#---------------------------------------------------#
#summary(fitw02b_c,standardized=TRUE, fit.measures=TRUE)
fitmeasures(fitw02b_c)[c(&quot;chisq.scaled&quot;,&quot;df&quot;,&quot;cfi&quot;,&quot;cfi.scaled&quot;,&quot;cfi.robust&quot;,&quot;rmsea&quot;,&quot;rmsea.scaled&quot;,&quot;rmsea.robust&quot;)]
semPlot::semPaths(object = fitw02b_c,what = &quot;std&quot;,thresholds = FALSE, intercepts = FALSE, curve=2)</code></pre>
<p><img src="prod_analysis-cfa_files/figure-html/unnamed-chunk-35-1.png" width="672" /></p>
<pre class="r"><code>#summary(fitw02b_o,standardized=TRUE, fit.measures=TRUE)
fitmeasures(fitw02b_o)[c(&quot;chisq.scaled&quot;,&quot;df&quot;,&quot;cfi&quot;,&quot;cfi.scaled&quot;,&quot;cfi.robust&quot;,&quot;rmsea&quot;,&quot;rmsea.scaled&quot;,&quot;rmsea.robust&quot;)]
semPlot::semPaths(object = fitw02b_o,what = &quot;std&quot;,thresholds = FALSE, intercepts = FALSE, curve=2)</code></pre>
<p><img src="prod_analysis-cfa_files/figure-html/unnamed-chunk-35-2.png" width="672" /></p>
<pre><code>## chisq.scaled           df          cfi   cfi.scaled   cfi.robust        rmsea rmsea.scaled 
##  21.89512187  14.00000000   0.98686103   0.98728536   0.98891906   0.03601966   0.03102177 
## rmsea.robust 
##   0.03291156 
## chisq.scaled           df          cfi   cfi.scaled   cfi.robust        rmsea rmsea.scaled 
##  32.82736205  14.00000000   0.99739823   0.98732355           NA   0.02531526   0.04794604 
## rmsea.robust 
##           NA</code></pre>
</div>
<div id="cfa-muestra-desigualdad" class="section level2" number="4.5">
<h2 number="4.5"><span class="header-section-number">4.5</span> CFA Muestra Desigualdad</h2>
<pre class="r"><code>w02des &lt;- data02 %&gt;% filter(FL_6_DO_Tratamiento_desigualdad==1) %&gt;% select(starts_with(&quot;meritv03_p&quot;)) </code></pre>
<table style="text-align:center">
<tr>
<td colspan="8" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
Statistic
</td>
<td>
N
</td>
<td>
Mean
</td>
<td>
St. Dev.
</td>
<td>
Min
</td>
<td>
Pctl(25)
</td>
<td>
Pctl(75)
</td>
<td>
Max
</td>
</tr>
<tr>
<td colspan="8" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
meritv03_perc_effort
</td>
<td>
591
</td>
<td>
3.244
</td>
<td>
1.219
</td>
<td>
1.000
</td>
<td>
2.000
</td>
<td>
4.000
</td>
<td>
5.000
</td>
</tr>
<tr>
<td style="text-align:left">
meritv03_perc_talent
</td>
<td>
591
</td>
<td>
3.069
</td>
<td>
1.099
</td>
<td>
1.000
</td>
<td>
2.000
</td>
<td>
4.000
</td>
<td>
5.000
</td>
</tr>
<tr>
<td style="text-align:left">
meritv03_perc_wpart
</td>
<td>
591
</td>
<td>
3.611
</td>
<td>
1.311
</td>
<td>
1.000
</td>
<td>
3.000
</td>
<td>
5.000
</td>
<td>
5.000
</td>
</tr>
<tr>
<td style="text-align:left">
meritv03_perc_netw
</td>
<td>
591
</td>
<td>
3.572
</td>
<td>
1.255
</td>
<td>
1.000
</td>
<td>
3.000
</td>
<td>
4.000
</td>
<td>
5.000
</td>
</tr>
<tr>
<td style="text-align:left">
meritv03_pref_effort
</td>
<td>
591
</td>
<td>
3.939
</td>
<td>
1.130
</td>
<td>
1.000
</td>
<td>
3.000
</td>
<td>
5.000
</td>
<td>
5.000
</td>
</tr>
<tr>
<td style="text-align:left">
meritv03_pref_talent
</td>
<td>
591
</td>
<td>
3.281
</td>
<td>
1.132
</td>
<td>
1.000
</td>
<td>
3.000
</td>
<td>
4.000
</td>
<td>
5.000
</td>
</tr>
<tr>
<td style="text-align:left">
meritv03_pref_wpart
</td>
<td>
591
</td>
<td>
2.579
</td>
<td>
1.173
</td>
<td>
1.000
</td>
<td>
2.000
</td>
<td>
3.000
</td>
<td>
5.000
</td>
</tr>
<tr>
<td style="text-align:left">
meritv03_pref_netw
</td>
<td>
591
</td>
<td>
2.272
</td>
<td>
1.034
</td>
<td>
1.000
</td>
<td>
1.000
</td>
<td>
3.000
</td>
<td>
5.000
</td>
</tr>
<tr>
<td colspan="8" style="border-bottom: 1px solid black">
</td>
</tr>
</table>
<pre class="r"><code>corw02_3&lt;-polychoric(w02des)
corrplot(corw02_3$rho, type = &quot;upper&quot;, order = &quot;hclust&quot;, tl.col = &quot;black&quot;, tl.srt = 45,addCoef.col = &quot;black&quot;,diag = FALSE)</code></pre>
<p><img src="prod_analysis-cfa_files/figure-html/unnamed-chunk-38-1.png" width="672" /></p>
<pre class="r"><code>model03 &lt;- &#39;
perc_merit=~meritv03_perc_effort+meritv03_perc_talent
perc_nmerit=~meritv03_perc_wpart+meritv03_perc_netw  
pref_merit=~meritv03_pref_effort+meritv03_pref_talent 
pref_nmerit=~meritv03_pref_wpart+meritv03_pref_netw&#39;

fitw02c_c &lt;- cfa(model = model03,data = w02des,estimator=&quot;MLR&quot;) # Continuo/ estimador ML Robust

fitw02c_o &lt;- cfa(model = model03,data = w02des,ordered = c(&quot;meritv03_perc_effort&quot;,&quot;meritv03_perc_talent&quot;,
                                                           &quot;meritv03_perc_wpart&quot;,&quot;meritv03_perc_netw&quot;,
                                                           &quot;meritv03_pref_effort&quot;,&quot;meritv03_pref_talent&quot;,
                                                           &quot;meritv03_pref_wpart&quot;,&quot;meritv03_pref_netw&quot;))
#---------------------------------------------------#
#summary(fitw02c_c,standardized=TRUE, fit.measures=TRUE)
fitmeasures(fitw02c_c)[c(&quot;chisq.scaled&quot;,&quot;df&quot;,&quot;cfi&quot;,&quot;cfi.scaled&quot;,&quot;cfi.robust&quot;,&quot;rmsea&quot;,&quot;rmsea.scaled&quot;,&quot;rmsea.robust&quot;)]
semPlot::semPaths(object = fitw02c_c,what = &quot;std&quot;,thresholds = FALSE, intercepts = FALSE)</code></pre>
<p><img src="prod_analysis-cfa_files/figure-html/unnamed-chunk-39-1.png" width="672" /></p>
<pre class="r"><code>#summary(fitw02b_o,standardized=TRUE, fit.measures=TRUE)
fitmeasures(fitw02c_o)[c(&quot;chisq.scaled&quot;,&quot;df&quot;,&quot;cfi&quot;,&quot;cfi.scaled&quot;,&quot;cfi.robust&quot;,&quot;rmsea&quot;,&quot;rmsea.scaled&quot;,&quot;rmsea.robust&quot;)]
semPlot::semPaths(object = fitw02c_o,what = &quot;std&quot;,thresholds = FALSE, intercepts = FALSE)</code></pre>
<p><img src="prod_analysis-cfa_files/figure-html/unnamed-chunk-39-2.png" width="672" /></p>
<pre><code>## chisq.scaled           df          cfi   cfi.scaled   cfi.robust        rmsea rmsea.scaled 
##  46.32268992  14.00000000   0.93940521   0.92687174   0.93936161   0.06371050   0.06250230 
## rmsea.robust 
##   0.06334778 
## chisq.scaled           df          cfi   cfi.scaled   cfi.robust        rmsea rmsea.scaled 
##  69.67269301  14.00000000   0.97297449   0.94366656           NA   0.06420276   0.08209772 
## rmsea.robust 
##           NA</code></pre>
</div>
</div>
<div id="resumen-ajuste-ola-2" class="section level1" number="5">
<h1 number="5"><span class="header-section-number">5</span> Resumen ajuste ola 2</h1>
<pre class="r"><code>sum_fitw02&lt;- bind_rows(fitmeasures(fitw02_c)[ c(&quot;cfi&quot;,&quot;cfi.scaled&quot;,&quot;cfi.robust&quot;,&quot;rmsea&quot;,&quot;rmsea.scaled&quot;,&quot;rmsea.robust&quot;)],
                       fitmeasures(fitw02_o)[ c(&quot;cfi&quot;,&quot;cfi.scaled&quot;,&quot;cfi.robust&quot;,&quot;rmsea&quot;,&quot;rmsea.scaled&quot;,&quot;rmsea.robust&quot;)],
                       fitmeasures(fitw02a_c)[c(&quot;cfi&quot;,&quot;cfi.scaled&quot;,&quot;cfi.robust&quot;,&quot;rmsea&quot;,&quot;rmsea.scaled&quot;,&quot;rmsea.robust&quot;)],
                       fitmeasures(fitw02a_o)[c(&quot;cfi&quot;,&quot;cfi.scaled&quot;,&quot;cfi.robust&quot;,&quot;rmsea&quot;,&quot;rmsea.scaled&quot;,&quot;rmsea.robust&quot;)],
                       fitmeasures(fitw02b_c)[c(&quot;cfi&quot;,&quot;cfi.scaled&quot;,&quot;cfi.robust&quot;,&quot;rmsea&quot;,&quot;rmsea.scaled&quot;,&quot;rmsea.robust&quot;)],
                       fitmeasures(fitw02b_o)[c(&quot;cfi&quot;,&quot;cfi.scaled&quot;,&quot;cfi.robust&quot;,&quot;rmsea&quot;,&quot;rmsea.scaled&quot;,&quot;rmsea.robust&quot;)],
                       fitmeasures(fitw02c_c)[c(&quot;cfi&quot;,&quot;cfi.scaled&quot;,&quot;cfi.robust&quot;,&quot;rmsea&quot;,&quot;rmsea.scaled&quot;,&quot;rmsea.robust&quot;)],
                       fitmeasures(fitw02c_c)[c(&quot;cfi&quot;,&quot;cfi.scaled&quot;,&quot;cfi.robust&quot;,&quot;rmsea&quot;,&quot;rmsea.scaled&quot;,&quot;rmsea.robust&quot;)])

sum_fitw02$mod &lt;- c(&quot;Modelo 1&quot;,&quot;Modelo 1&quot;,&quot;Modelo 2&quot;,&quot;Modelo 2&quot;,&quot;Modelo 3&quot;,&quot;Modelo 3&quot;,&quot;Modelo 4&quot;,&quot;Modelo 4&quot;)
sum_fitw02$est &lt;- c(&quot;Continuo&quot;,&quot;Ordinal&quot;,&quot;Continuo&quot;,&quot;Ordinal&quot;,&quot;Continuo&quot;,&quot;Ordinal&quot;,&quot;Continuo&quot;,&quot;Ordinal&quot;)
sum_fitw02 &lt;- select(sum_fitw02,mod,est,everything())

kable(sum_fitw02,digits = 3,format = &quot;html&quot;,row.names = F,booktabs=T, caption = &quot;Resumen ajuste ola 2&quot;) %&gt;% 
  kable_styling(full_width = F) %&gt;% 
  collapse_rows(columns = 1,valign = &quot;middle&quot;) %&gt;% 
  footnote(number = c(&quot;Modelo 1: Muestra completa&quot;, 
                      &quot;Modelo 2: Muestra grupo Control&quot;, 
                      &quot;Modelo 3: Muestra grupo tratamiento pobreza&quot;,
                      &quot;Modelo 4: Muestra grupo tratamiento desigualdad&quot;))</code></pre>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
Resumen ajuste ola 2
</caption>
<thead>
<tr>
<th style="text-align:left;">
mod
</th>
<th style="text-align:left;">
est
</th>
<th style="text-align:right;">
cfi
</th>
<th style="text-align:right;">
cfi.scaled
</th>
<th style="text-align:right;">
cfi.robust
</th>
<th style="text-align:right;">
rmsea
</th>
<th style="text-align:right;">
rmsea.scaled
</th>
<th style="text-align:right;">
rmsea.robust
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;vertical-align: middle !important;" rowspan="2">
Modelo 1
</td>
<td style="text-align:left;">
Continuo
</td>
<td style="text-align:right;">
0.967
</td>
<td style="text-align:right;">
0.965
</td>
<td style="text-align:right;">
0.968
</td>
<td style="text-align:right;">
0.051
</td>
<td style="text-align:right;">
0.046
</td>
<td style="text-align:right;">
0.050
</td>
</tr>
<tr>
<td style="text-align:left;">
Ordinal
</td>
<td style="text-align:right;">
0.988
</td>
<td style="text-align:right;">
0.975
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
0.047
</td>
<td style="text-align:right;">
0.060
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:left;vertical-align: middle !important;" rowspan="2">
Modelo 2
</td>
<td style="text-align:left;">
Continuo
</td>
<td style="text-align:right;">
0.953
</td>
<td style="text-align:right;">
0.952
</td>
<td style="text-align:right;">
0.957
</td>
<td style="text-align:right;">
0.057
</td>
<td style="text-align:right;">
0.050
</td>
<td style="text-align:right;">
0.054
</td>
</tr>
<tr>
<td style="text-align:left;">
Ordinal
</td>
<td style="text-align:right;">
0.988
</td>
<td style="text-align:right;">
0.975
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
0.043
</td>
<td style="text-align:right;">
0.057
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:left;vertical-align: middle !important;" rowspan="2">
Modelo 3
</td>
<td style="text-align:left;">
Continuo
</td>
<td style="text-align:right;">
0.987
</td>
<td style="text-align:right;">
0.987
</td>
<td style="text-align:right;">
0.989
</td>
<td style="text-align:right;">
0.036
</td>
<td style="text-align:right;">
0.031
</td>
<td style="text-align:right;">
0.033
</td>
</tr>
<tr>
<td style="text-align:left;">
Ordinal
</td>
<td style="text-align:right;">
0.997
</td>
<td style="text-align:right;">
0.987
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
0.025
</td>
<td style="text-align:right;">
0.048
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:left;vertical-align: middle !important;" rowspan="2">
Modelo 4
</td>
<td style="text-align:left;">
Continuo
</td>
<td style="text-align:right;">
0.939
</td>
<td style="text-align:right;">
0.927
</td>
<td style="text-align:right;">
0.939
</td>
<td style="text-align:right;">
0.064
</td>
<td style="text-align:right;">
0.063
</td>
<td style="text-align:right;">
0.063
</td>
</tr>
<tr>
<td style="text-align:left;">
Ordinal
</td>
<td style="text-align:right;">
0.939
</td>
<td style="text-align:right;">
0.927
</td>
<td style="text-align:right;">
0.939
</td>
<td style="text-align:right;">
0.064
</td>
<td style="text-align:right;">
0.063
</td>
<td style="text-align:right;">
0.063
</td>
</tr>
</tbody>
<tfoot>
<tr>
<td style="padding: 0; border: 0;" colspan="100%">
<sup>1</sup> Modelo 1: Muestra completa
</td>
</tr>
<tr>
<td style="padding: 0; border: 0;" colspan="100%">
<sup>2</sup> Modelo 2: Muestra grupo Control
</td>
</tr>
<tr>
<td style="padding: 0; border: 0;" colspan="100%">
<sup>3</sup> Modelo 3: Muestra grupo tratamiento pobreza
</td>
</tr>
<tr>
<td style="padding: 0; border: 0;" colspan="100%">
<sup>4</sup> Modelo 4: Muestra grupo tratamiento desigualdad
</td>
</tr>
</tfoot>
</table>
</div>
<div id="wave-03" class="section level1" number="6">
<h1 number="6"><span class="header-section-number">6</span> Wave 03</h1>
<pre class="r"><code>data03 &lt;- sjlabelled::read_spss(path = &quot;input/data/original/Estudio_3_ola3.sav&quot;,verbose = FALSE)
dat01 &lt;- data03 %&gt;% select(starts_with(&quot;meritv03_p&quot;)) </code></pre>
<pre class="r"><code>sjt.fa(data = dat01,show.comm = TRUE)</code></pre>
<pre><code>## Parallel analysis suggests that the number of factors =  3  and the number of components =  NA</code></pre>
<table style="border-collapse:collapse; border:none;">
<caption style="font-weight: bold; text-align:left;">
Factor Analysis
</caption>
<tr>
<th style="border-top:double black; padding:0.2cm;">
 
</th>
<th style="border-top:double black; padding:0.2cm;">
Factor 1
</th>
<th style="border-top:double black; padding:0.2cm;">
Factor 2
</th>
<th style="border-top:double black; padding:0.2cm;">
Factor 3
</th>
<th style="border-top:double black; padding:0.2cm; font-style:italic; color:#666666;">
Communality
</th>
</tr>
<tr>
<td style=" border-top:1px solid black;">
Pensando en la sociedad chilena, Â¿En quÃ©<br>medida se encuentra usted de acuerdo o<br>en desacuerdo con cada una de las<br>siguientes afirmaciones? - Quienes mÃ¡s<br>se esfuerzan logran obtener mayores<br>recompensas que quienes se esfuerzan<br>menos.
</td>
<td style="padding:0.2cm; text-align:center; border-top:1px solid black;">
0.66
</td>
<td style="padding:0.2cm; text-align:center; color:#cccccc; border-top:1px solid black;">
-0.28
</td>
<td style="padding:0.2cm; text-align:center; color:#cccccc; border-top:1px solid black;">
0.09
</td>
<td style="padding:0.2cm; font-style:italic; color:#666666; text-align:center; border-top:1px solid black;">
0.45
</td>
</tr>
<tr>
<td style>
Pensando en la sociedad chilena, Â¿En quÃ©<br>medida se encuentra usted de acuerdo o<br>en desacuerdo con cada una de las<br>siguientes afirmaciones? - Quienes<br>poseen mÃ¡s talento logran obtener<br>mayores recompensas que quienes poseen<br>menos talento.
</td>
<td style="padding:0.2cm; text-align:center;">
0.58
</td>
<td style="padding:0.2cm; text-align:center; color:#cccccc;">
-0.09
</td>
<td style="padding:0.2cm; text-align:center; color:#cccccc;">
0.13
</td>
<td style="padding:0.2cm; font-style:italic; color:#666666; text-align:center;">
0.36
</td>
</tr>
<tr>
<td style>
Pensando en la sociedad chilena, Â¿En quÃ©<br>medida se encuentra usted de acuerdo o<br>en desacuerdo con cada una de las<br>siguientes afirmaciones? - Quienes<br>tienen padres ricos logran salir<br>adelante.
</td>
<td style="padding:0.2cm; text-align:center; color:#cccccc;">
-0.05
</td>
<td style="padding:0.2cm; text-align:center;">
0.73
</td>
<td style="padding:0.2cm; text-align:center; color:#cccccc;">
0.08
</td>
<td style="padding:0.2cm; font-style:italic; color:#666666; text-align:center;">
0.52
</td>
</tr>
<tr>
<td style>
Pensando en la sociedad chilena, Â¿En quÃ©<br>medida se encuentra usted de acuerdo o<br>en desacuerdo con cada una de las<br>siguientes afirmaciones? - Quienes<br>tienen buenos contactos logran salir<br>adelante.
</td>
<td style="padding:0.2cm; text-align:center; color:#cccccc;">
-0.02
</td>
<td style="padding:0.2cm; text-align:center;">
0.71
</td>
<td style="padding:0.2cm; text-align:center; color:#cccccc;">
0.09
</td>
<td style="padding:0.2cm; font-style:italic; color:#666666; text-align:center;">
0.50
</td>
</tr>
<tr>
<td style>
Pensando en la sociedad chilena, Â¿En quÃ©<br>medida se encuentra usted de acuerdo o<br>en desacuerdo con cada una de las<br>siguientes afirmaciones? - Quienes mÃ¡s<br>se esfuerzan deberÃ­an obtener mayores<br>recompensas que quienes se esfuerzan<br>menos.
</td>
<td style="padding:0.2cm; text-align:center;">
0.55
</td>
<td style="padding:0.2cm; text-align:center; color:#cccccc;">
0.19
</td>
<td style="padding:0.2cm; text-align:center; color:#cccccc;">
-0.15
</td>
<td style="padding:0.2cm; font-style:italic; color:#666666; text-align:center;">
0.39
</td>
</tr>
<tr>
<td style>
Pensando en la sociedad chilena, Â¿En quÃ©<br>medida se encuentra usted de acuerdo o<br>en desacuerdo con cada una de las<br>siguientes afirmaciones? - Quienes<br>poseen mÃ¡s talento deberÃ­an obtener<br>mayores recompensas que quienes poseen<br>menos talento.
</td>
<td style="padding:0.2cm; text-align:center;">
0.43
</td>
<td style="padding:0.2cm; text-align:center; color:#cccccc;">
0.23
</td>
<td style="padding:0.2cm; text-align:center; color:#cccccc;">
-0.07
</td>
<td style="padding:0.2cm; font-style:italic; color:#666666; text-align:center;">
0.28
</td>
</tr>
<tr>
<td style>
Pensando en la sociedad chilena, Â¿En quÃ©<br>medida se encuentra usted de acuerdo o<br>en desacuerdo con cada una de las<br>siguientes afirmaciones? - EstÃ¡ bien que<br>quienes tienen padres ricos salgan<br>adelante.
</td>
<td style="padding:0.2cm; text-align:center; color:#cccccc;">
0.03
</td>
<td style="padding:0.2cm; text-align:center; color:#cccccc;">
0.13
</td>
<td style="padding:0.2cm; text-align:center;">
0.75
</td>
<td style="padding:0.2cm; font-style:italic; color:#666666; text-align:center;">
0.58
</td>
</tr>
<tr>
<td style>
Pensando en la sociedad chilena, Â¿En quÃ©<br>medida se encuentra usted de acuerdo o<br>en desacuerdo con cada una de las<br>siguientes afirmaciones? - EstÃ¡ bien que<br>quienes tienen buenos contactos salgan<br>adelante.
</td>
<td style="padding:0.2cm; text-align:center; color:#cccccc;">
0.02
</td>
<td style="padding:0.2cm; text-align:center; color:#cccccc;">
0.06
</td>
<td style="padding:0.2cm; text-align:center;">
0.69
</td>
<td style="padding:0.2cm; font-style:italic; color:#666666; text-align:center;">
0.49
</td>
</tr>
<tr>
<td style="padding:0.2cm; font-style:italic;">
Total Communalities
</td>
<td style="padding:0.2cm; text-align:center; font-style:italic;" colspan="3">
</td>
<td style="padding:0.2cm; text-align:center; font-style:italic;">
3.58
</td>
</tr>
<tr>
<td style="padding:0.2cm; font-style:italic; border-bottom:double;">
Cronbach’s α
</td>
<td style="padding:0.2cm; text-align:center; font-style:italic; border-bottom:double;">
0.62
</td>
<td style="padding:0.2cm; text-align:center; font-style:italic; border-bottom:double;">
0.68
</td>
<td style="padding:0.2cm; text-align:center; font-style:italic; border-bottom:double;">
0.69
</td>
<td style="padding:0.2cm; text-align:center; font-style:italic; border-bottom:double;">
</td>
</tr>
</table>
<pre class="r"><code>model03 &lt;- &#39;
perc_merit=~meritv03_perc_effort+meritv03_perc_talent 
perc_nmerit=~meritv03_perc_wpart+meritv03_perc_netw  
pref_merit=~meritv03_pref_effort+meritv03_pref_talent 
pref_nmerit=~meritv03_pref_wpart+meritv03_pref_netw&#39;

fitw03c_c &lt;- cfa(model = model03,data = dat01,estimator=&quot;MLR&quot;) # Continuo/ estimador ML Robust

fitw03c_o &lt;- cfa(model = model03,data = dat01,ordered = c(&quot;meritv03_perc_effort&quot;,&quot;meritv03_perc_talent&quot;,
                                                          &quot;meritv03_perc_wpart&quot;,&quot;meritv03_perc_netw&quot;,
                                                          &quot;meritv03_pref_effort&quot;,&quot;meritv03_pref_talent&quot;,
                                                          &quot;meritv03_pref_wpart&quot;,&quot;meritv03_pref_netw&quot;))
#---------------------------------------------------#
#summary(fitw03c_c,standardized=TRUE, fit.measures=TRUE)
fitmeasures(fitw03c_c)[c(&quot;chisq.scaled&quot;,&quot;df&quot;,&quot;cfi&quot;,&quot;cfi.scaled&quot;,&quot;cfi.robust&quot;,&quot;rmsea&quot;,&quot;rmsea.scaled&quot;,&quot;rmsea.robust&quot;)]

#summary(fitw03c_o,standardized=TRUE, fit.measures=TRUE)
fitmeasures(fitw03c_o)[c(&quot;chisq.scaled&quot;,&quot;df&quot;,&quot;cfi&quot;,&quot;cfi.scaled&quot;,&quot;cfi.robust&quot;,&quot;rmsea&quot;,&quot;rmsea.scaled&quot;,&quot;rmsea.robust&quot;)]</code></pre>
<pre><code>## chisq.scaled           df          cfi   cfi.scaled   cfi.robust        rmsea rmsea.scaled 
##  62.42098851  14.00000000   0.97001271   0.96743840   0.97104967   0.05354429   0.04868836 
## rmsea.robust 
##   0.05249427 
## chisq.scaled           df          cfi   cfi.scaled   cfi.robust        rmsea rmsea.scaled 
## 106.11132208  14.00000000   0.98842335   0.97425449           NA   0.05216642   0.06717594 
## rmsea.robust 
##           NA</code></pre>
<p><strong>summary</strong> &gt; * Ajuste usando estimador MLR es bueno (CFI = 0.971, RMSEA = 0.052). El chi2 (robusto) es 62.421<br />
&gt; * Ajuste usando estimador DWLS es bueno (CFI = 0.974, RMSEA = 0.067). El chi2 (robusto) es 106.111</p>
</div>
<div id="resumen-ajuste-ola-3" class="section level1" number="7">
<h1 number="7"><span class="header-section-number">7</span> Resumen ajuste ola 3</h1>
<pre class="r"><code>sum_fitw03&lt;- bind_rows(fitmeasures(fitw03c_c)[ c(&quot;cfi&quot;,&quot;cfi.scaled&quot;,&quot;cfi.robust&quot;,&quot;rmsea&quot;,&quot;rmsea.scaled&quot;,&quot;rmsea.robust&quot;)],
                       fitmeasures(fitw03c_o)[ c(&quot;cfi&quot;,&quot;cfi.scaled&quot;,&quot;cfi.robust&quot;,&quot;rmsea&quot;,&quot;rmsea.scaled&quot;,&quot;rmsea.robust&quot;)])

sum_fitw03$mod &lt;- c(&quot;Modelo 1&quot;,&quot;Modelo 1&quot;)
sum_fitw03$est &lt;- c(&quot;Continuo&quot;,&quot;Ordinal&quot;)
sum_fitw03 &lt;- select(sum_fitw03,mod,est,everything())

kable(sum_fitw03,digits = 3,format = &quot;html&quot;,row.names = F,booktabs=T,caption = &quot;Resumen ajuste ola 3&quot;) %&gt;% 
  kable_styling(full_width = F) %&gt;% 
  collapse_rows(columns = 1,valign = &quot;middle&quot;) %&gt;% 
  footnote(number = c(&quot;Modelo 1: Muestra completa&quot;))</code></pre>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
Resumen ajuste ola 3
</caption>
<thead>
<tr>
<th style="text-align:left;">
mod
</th>
<th style="text-align:left;">
est
</th>
<th style="text-align:right;">
cfi
</th>
<th style="text-align:right;">
cfi.scaled
</th>
<th style="text-align:right;">
cfi.robust
</th>
<th style="text-align:right;">
rmsea
</th>
<th style="text-align:right;">
rmsea.scaled
</th>
<th style="text-align:right;">
rmsea.robust
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;vertical-align: middle !important;" rowspan="2">
Modelo 1
</td>
<td style="text-align:left;">
Continuo
</td>
<td style="text-align:right;">
0.970
</td>
<td style="text-align:right;">
0.967
</td>
<td style="text-align:right;">
0.971
</td>
<td style="text-align:right;">
0.054
</td>
<td style="text-align:right;">
0.049
</td>
<td style="text-align:right;">
0.052
</td>
</tr>
<tr>
<td style="text-align:left;">
Ordinal
</td>
<td style="text-align:right;">
0.988
</td>
<td style="text-align:right;">
0.974
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
0.052
</td>
<td style="text-align:right;">
0.067
</td>
<td style="text-align:right;">
</td>
</tr>
</tbody>
<tfoot>
<tr>
<td style="padding: 0; border: 0;" colspan="100%">
<sup>1</sup> Modelo 1: Muestra completa
</td>
</tr>
</tfoot>
</table>
</div>
<div id="análisis-longitudinal" class="section level1" number="8">
<h1 number="8"><span class="header-section-number">8</span> Análisis longitudinal</h1>
<pre class="r"><code>library(sjPlot)
library(dplyr)
library(lavaan)
library(stargazer)
library(corrplot)
library(psych)
library(knitr)
library(kableExtra)
load(file = &quot;input/data/proc/datawide_123.RData&quot;)</code></pre>
<div id="correlación-indicadores-w01-y-w02" class="section level2" number="8.1">
<h2 number="8.1"><span class="header-section-number">8.1</span> Correlación indicadores w01 y w02</h2>
<pre class="r"><code>g01&lt;- wide02 %&gt;% filter(grupo==1) %&gt;% select(starts_with(&quot;perc_&quot;),starts_with(&quot;pref_&quot;)) # Fixed by perception/preference
g02&lt;- wide02 %&gt;% filter(grupo==2) %&gt;% select(starts_with(&quot;perc_&quot;),starts_with(&quot;pref_&quot;)) # Fixed by topic (i.e: effort)
g03&lt;- wide02 %&gt;% filter(grupo==3) %&gt;% select(starts_with(&quot;perc_&quot;),starts_with(&quot;pref_&quot;)) # Randomized</code></pre>
<div id="grupo-versión-01" class="section level3" number="8.1.1">
<h3 number="8.1.1"><span class="header-section-number">8.1.1</span> Grupo Versión 01</h3>
<pre class="r"><code>stargazer(g01,type = &quot;html&quot;, median = T,digits = 2)</code></pre>
<table style="text-align:center">
<tr>
<td colspan="9" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
Statistic
</td>
<td>
N
</td>
<td>
Mean
</td>
<td>
St. Dev.
</td>
<td>
Min
</td>
<td>
Pctl(25)
</td>
<td>
Median
</td>
<td>
Pctl(75)
</td>
<td>
Max
</td>
</tr>
<tr>
<td colspan="9" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
perc_effort_w1
</td>
<td>
486
</td>
<td>
3.22
</td>
<td>
1.35
</td>
<td>
1
</td>
<td>
2
</td>
<td>
3
</td>
<td>
4
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
perc_talent_w1
</td>
<td>
486
</td>
<td>
3.02
</td>
<td>
1.11
</td>
<td>
1
</td>
<td>
2
</td>
<td>
3
</td>
<td>
4
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
perc_wpart_w1
</td>
<td>
486
</td>
<td>
3.61
</td>
<td>
1.36
</td>
<td>
1
</td>
<td>
3
</td>
<td>
4
</td>
<td>
5
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
perc_netw_w1
</td>
<td>
486
</td>
<td>
3.76
</td>
<td>
1.23
</td>
<td>
1
</td>
<td>
3
</td>
<td>
4
</td>
<td>
5
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
perc_effort_w2
</td>
<td>
486
</td>
<td>
3.33
</td>
<td>
1.23
</td>
<td>
1
</td>
<td>
2
</td>
<td>
3.5
</td>
<td>
4
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
perc_talent_w2
</td>
<td>
486
</td>
<td>
3.13
</td>
<td>
1.09
</td>
<td>
1
</td>
<td>
2
</td>
<td>
3
</td>
<td>
4
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
perc_wpart_w2
</td>
<td>
486
</td>
<td>
3.59
</td>
<td>
1.30
</td>
<td>
1
</td>
<td>
3
</td>
<td>
4
</td>
<td>
5
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
perc_netw_w2
</td>
<td>
486
</td>
<td>
3.56
</td>
<td>
1.26
</td>
<td>
1
</td>
<td>
3
</td>
<td>
4
</td>
<td>
4
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
perc_effort_w3
</td>
<td>
486
</td>
<td>
3.47
</td>
<td>
1.16
</td>
<td>
1
</td>
<td>
3
</td>
<td>
4
</td>
<td>
4
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
perc_talent_w3
</td>
<td>
486
</td>
<td>
3.18
</td>
<td>
1.01
</td>
<td>
1
</td>
<td>
3
</td>
<td>
3
</td>
<td>
4
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
perc_wpart_w3
</td>
<td>
486
</td>
<td>
3.38
</td>
<td>
1.30
</td>
<td>
1
</td>
<td>
3
</td>
<td>
4
</td>
<td>
4
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
perc_netw_w3
</td>
<td>
486
</td>
<td>
3.52
</td>
<td>
1.20
</td>
<td>
1
</td>
<td>
3
</td>
<td>
4
</td>
<td>
4
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
pref_effort_w1
</td>
<td>
486
</td>
<td>
3.91
</td>
<td>
1.24
</td>
<td>
1
</td>
<td>
3
</td>
<td>
4
</td>
<td>
5
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
pref_talent_w1
</td>
<td>
486
</td>
<td>
3.33
</td>
<td>
1.15
</td>
<td>
1
</td>
<td>
3
</td>
<td>
3
</td>
<td>
4
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
pref_wpart_w1
</td>
<td>
486
</td>
<td>
2.54
</td>
<td>
1.12
</td>
<td>
1
</td>
<td>
2
</td>
<td>
3
</td>
<td>
3
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
pref_netw_w1
</td>
<td>
486
</td>
<td>
2.30
</td>
<td>
1.06
</td>
<td>
1
</td>
<td>
1
</td>
<td>
2
</td>
<td>
3
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
pref_effort_w2
</td>
<td>
486
</td>
<td>
3.92
</td>
<td>
1.13
</td>
<td>
1
</td>
<td>
3
</td>
<td>
4
</td>
<td>
5
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
pref_talent_w2
</td>
<td>
486
</td>
<td>
3.30
</td>
<td>
1.10
</td>
<td>
1
</td>
<td>
3
</td>
<td>
3
</td>
<td>
4
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
pref_wpart_w2
</td>
<td>
486
</td>
<td>
2.60
</td>
<td>
1.14
</td>
<td>
1
</td>
<td>
2
</td>
<td>
3
</td>
<td>
3
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
pref_netw_w2
</td>
<td>
486
</td>
<td>
2.29
</td>
<td>
1.09
</td>
<td>
1
</td>
<td>
1
</td>
<td>
2
</td>
<td>
3
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
pref_effort_w3
</td>
<td>
486
</td>
<td>
4.03
</td>
<td>
1.11
</td>
<td>
1
</td>
<td>
4
</td>
<td>
4
</td>
<td>
5
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
pref_talent_w3
</td>
<td>
486
</td>
<td>
3.49
</td>
<td>
1.01
</td>
<td>
1
</td>
<td>
3
</td>
<td>
4
</td>
<td>
4
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
pref_wpart_w3
</td>
<td>
486
</td>
<td>
2.51
</td>
<td>
1.16
</td>
<td>
1
</td>
<td>
2
</td>
<td>
3
</td>
<td>
3
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
pref_netw_w3
</td>
<td>
486
</td>
<td>
2.35
</td>
<td>
1.08
</td>
<td>
1
</td>
<td>
2
</td>
<td>
2
</td>
<td>
3
</td>
<td>
5
</td>
</tr>
<tr>
<td colspan="9" style="border-bottom: 1px solid black">
</td>
</tr>
</table>
<pre class="r"><code>corwide01a&lt;- polychoric(x = select(g01 ,starts_with(match = &quot;perc_&quot;)),na.rm = T)
corrplot(corwide01a$rho, method = &quot;color&quot; ,type = &quot;upper&quot;, tl.col = &quot;black&quot;, tl.srt = 45,addCoef.col = &quot;black&quot;,diag = FALSE)</code></pre>
<div class="figure" style="text-align: center">
<img src="prod_analysis-cfa_files/figure-html/unnamed-chunk-48-1.png" alt="Percepción" width="75%" />
<p class="caption">
Percepción
</p>
</div>
<pre class="r"><code>corwide01b&lt;- polychoric(x = select(g01 ,starts_with(match = &quot;pref_&quot;)),na.rm = T)
corrplot(corwide01b$rho, method = &quot;color&quot; ,type = &quot;upper&quot;, tl.col = &quot;black&quot;, tl.srt = 45,addCoef.col = &quot;black&quot;,diag = FALSE)</code></pre>
<div class="figure" style="text-align: center">
<img src="prod_analysis-cfa_files/figure-html/unnamed-chunk-48-2.png" alt="Preferencia" width="75%" />
<p class="caption">
Preferencia
</p>
</div>
</div>
<div id="grupo-versión-02" class="section level3" number="8.1.2">
<h3 number="8.1.2"><span class="header-section-number">8.1.2</span> Grupo Versión 02</h3>
<pre class="r"><code>stargazer(g02,type = &quot;html&quot;, median = T,digits = 2)</code></pre>
<table style="text-align:center">
<tr>
<td colspan="9" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
Statistic
</td>
<td>
N
</td>
<td>
Mean
</td>
<td>
St. Dev.
</td>
<td>
Min
</td>
<td>
Pctl(25)
</td>
<td>
Median
</td>
<td>
Pctl(75)
</td>
<td>
Max
</td>
</tr>
<tr>
<td colspan="9" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
perc_effort_w1
</td>
<td>
471
</td>
<td>
3.10
</td>
<td>
1.42
</td>
<td>
1
</td>
<td>
2
</td>
<td>
3
</td>
<td>
4
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
perc_talent_w1
</td>
<td>
471
</td>
<td>
3.09
</td>
<td>
1.13
</td>
<td>
1
</td>
<td>
2
</td>
<td>
3
</td>
<td>
4
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
perc_wpart_w1
</td>
<td>
471
</td>
<td>
3.65
</td>
<td>
1.36
</td>
<td>
1
</td>
<td>
3
</td>
<td>
4
</td>
<td>
5
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
perc_netw_w1
</td>
<td>
471
</td>
<td>
3.68
</td>
<td>
1.22
</td>
<td>
1
</td>
<td>
3
</td>
<td>
4
</td>
<td>
5
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
perc_effort_w2
</td>
<td>
471
</td>
<td>
3.35
</td>
<td>
1.25
</td>
<td>
1
</td>
<td>
2
</td>
<td>
4
</td>
<td>
4
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
perc_talent_w2
</td>
<td>
471
</td>
<td>
3.14
</td>
<td>
1.10
</td>
<td>
1
</td>
<td>
2
</td>
<td>
3
</td>
<td>
4
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
perc_wpart_w2
</td>
<td>
471
</td>
<td>
3.59
</td>
<td>
1.26
</td>
<td>
1
</td>
<td>
3
</td>
<td>
4
</td>
<td>
5
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
perc_netw_w2
</td>
<td>
471
</td>
<td>
3.61
</td>
<td>
1.20
</td>
<td>
1
</td>
<td>
3
</td>
<td>
4
</td>
<td>
4
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
perc_effort_w3
</td>
<td>
471
</td>
<td>
3.54
</td>
<td>
1.22
</td>
<td>
1
</td>
<td>
3
</td>
<td>
4
</td>
<td>
5
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
perc_talent_w3
</td>
<td>
471
</td>
<td>
3.21
</td>
<td>
1.06
</td>
<td>
1
</td>
<td>
2.5
</td>
<td>
3
</td>
<td>
4
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
perc_wpart_w3
</td>
<td>
471
</td>
<td>
3.41
</td>
<td>
1.27
</td>
<td>
1
</td>
<td>
3
</td>
<td>
4
</td>
<td>
4
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
perc_netw_w3
</td>
<td>
471
</td>
<td>
3.43
</td>
<td>
1.28
</td>
<td>
1
</td>
<td>
3
</td>
<td>
4
</td>
<td>
4
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
pref_effort_w1
</td>
<td>
471
</td>
<td>
3.75
</td>
<td>
1.34
</td>
<td>
1
</td>
<td>
3
</td>
<td>
4
</td>
<td>
5
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
pref_talent_w1
</td>
<td>
471
</td>
<td>
3.18
</td>
<td>
1.15
</td>
<td>
1
</td>
<td>
2
</td>
<td>
3
</td>
<td>
4
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
pref_wpart_w1
</td>
<td>
471
</td>
<td>
2.77
</td>
<td>
1.20
</td>
<td>
1
</td>
<td>
2
</td>
<td>
3
</td>
<td>
4
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
pref_netw_w1
</td>
<td>
471
</td>
<td>
2.39
</td>
<td>
1.09
</td>
<td>
1
</td>
<td>
2
</td>
<td>
2
</td>
<td>
3
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
pref_effort_w2
</td>
<td>
471
</td>
<td>
4.00
</td>
<td>
1.14
</td>
<td>
1
</td>
<td>
4
</td>
<td>
4
</td>
<td>
5
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
pref_talent_w2
</td>
<td>
471
</td>
<td>
3.27
</td>
<td>
1.15
</td>
<td>
1
</td>
<td>
2.5
</td>
<td>
3
</td>
<td>
4
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
pref_wpart_w2
</td>
<td>
471
</td>
<td>
2.59
</td>
<td>
1.15
</td>
<td>
1
</td>
<td>
2
</td>
<td>
3
</td>
<td>
3
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
pref_netw_w2
</td>
<td>
471
</td>
<td>
2.30
</td>
<td>
1.03
</td>
<td>
1
</td>
<td>
2
</td>
<td>
2
</td>
<td>
3
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
pref_effort_w3
</td>
<td>
471
</td>
<td>
4.11
</td>
<td>
1.08
</td>
<td>
1
</td>
<td>
4
</td>
<td>
4
</td>
<td>
5
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
pref_talent_w3
</td>
<td>
471
</td>
<td>
3.45
</td>
<td>
1.12
</td>
<td>
1
</td>
<td>
3
</td>
<td>
4
</td>
<td>
4
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
pref_wpart_w3
</td>
<td>
471
</td>
<td>
2.53
</td>
<td>
1.14
</td>
<td>
1
</td>
<td>
2
</td>
<td>
3
</td>
<td>
3
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
pref_netw_w3
</td>
<td>
471
</td>
<td>
2.28
</td>
<td>
1.05
</td>
<td>
1
</td>
<td>
1
</td>
<td>
2
</td>
<td>
3
</td>
<td>
5
</td>
</tr>
<tr>
<td colspan="9" style="border-bottom: 1px solid black">
</td>
</tr>
</table>
<pre class="r"><code>corwide02a&lt;- polychoric(x = select(g02 ,starts_with(match = &quot;perc_&quot;)),na.rm = T)
corrplot(corwide02a$rho, method = &quot;color&quot; ,type = &quot;upper&quot;, tl.col = &quot;black&quot;, tl.srt = 45,addCoef.col = &quot;black&quot;,diag = FALSE)</code></pre>
<div class="figure" style="text-align: center">
<img src="prod_analysis-cfa_files/figure-html/unnamed-chunk-50-1.png" alt="Percepción" width="75%" />
<p class="caption">
Percepción
</p>
</div>
<pre class="r"><code>corwide02b&lt;- polychoric(x = select(g02 ,starts_with(match = &quot;pref_&quot;)),na.rm = T)
corrplot(corwide02b$rho, method = &quot;color&quot; ,type = &quot;upper&quot;, tl.col = &quot;black&quot;, tl.srt = 45,addCoef.col = &quot;black&quot;,diag = FALSE)</code></pre>
<div class="figure" style="text-align: center">
<img src="prod_analysis-cfa_files/figure-html/unnamed-chunk-50-2.png" alt="Preferencia" width="75%" />
<p class="caption">
Preferencia
</p>
</div>
</div>
<div id="grupo-versión-03" class="section level3" number="8.1.3">
<h3 number="8.1.3"><span class="header-section-number">8.1.3</span> Grupo Versión 03</h3>
<pre class="r"><code>stargazer(g03,type = &quot;html&quot;, median = T,digits = 2)</code></pre>
<table style="text-align:center">
<tr>
<td colspan="9" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
Statistic
</td>
<td>
N
</td>
<td>
Mean
</td>
<td>
St. Dev.
</td>
<td>
Min
</td>
<td>
Pctl(25)
</td>
<td>
Median
</td>
<td>
Pctl(75)
</td>
<td>
Max
</td>
</tr>
<tr>
<td colspan="9" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
perc_effort_w1
</td>
<td>
491
</td>
<td>
3.41
</td>
<td>
1.34
</td>
<td>
1
</td>
<td>
2
</td>
<td>
4
</td>
<td>
5
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
perc_talent_w1
</td>
<td>
491
</td>
<td>
3.12
</td>
<td>
1.24
</td>
<td>
1
</td>
<td>
2
</td>
<td>
3
</td>
<td>
4
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
perc_wpart_w1
</td>
<td>
491
</td>
<td>
3.76
</td>
<td>
1.34
</td>
<td>
1
</td>
<td>
3
</td>
<td>
4
</td>
<td>
5
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
perc_netw_w1
</td>
<td>
491
</td>
<td>
3.92
</td>
<td>
1.22
</td>
<td>
1
</td>
<td>
3
</td>
<td>
4
</td>
<td>
5
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
perc_effort_w2
</td>
<td>
491
</td>
<td>
3.32
</td>
<td>
1.24
</td>
<td>
1
</td>
<td>
2
</td>
<td>
4
</td>
<td>
4
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
perc_talent_w2
</td>
<td>
491
</td>
<td>
3.13
</td>
<td>
1.09
</td>
<td>
1
</td>
<td>
2
</td>
<td>
3
</td>
<td>
4
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
perc_wpart_w2
</td>
<td>
491
</td>
<td>
3.44
</td>
<td>
1.41
</td>
<td>
1
</td>
<td>
2
</td>
<td>
4
</td>
<td>
5
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
perc_netw_w2
</td>
<td>
491
</td>
<td>
3.50
</td>
<td>
1.28
</td>
<td>
1
</td>
<td>
3
</td>
<td>
4
</td>
<td>
4
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
perc_effort_w3
</td>
<td>
491
</td>
<td>
3.49
</td>
<td>
1.23
</td>
<td>
1
</td>
<td>
3
</td>
<td>
4
</td>
<td>
4.5
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
perc_talent_w3
</td>
<td>
491
</td>
<td>
3.21
</td>
<td>
1.01
</td>
<td>
1
</td>
<td>
3
</td>
<td>
3
</td>
<td>
4
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
perc_wpart_w3
</td>
<td>
491
</td>
<td>
3.41
</td>
<td>
1.31
</td>
<td>
1
</td>
<td>
3
</td>
<td>
4
</td>
<td>
4
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
perc_netw_w3
</td>
<td>
491
</td>
<td>
3.40
</td>
<td>
1.25
</td>
<td>
1
</td>
<td>
3
</td>
<td>
4
</td>
<td>
4
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
pref_effort_w1
</td>
<td>
491
</td>
<td>
4.14
</td>
<td>
1.11
</td>
<td>
1
</td>
<td>
4
</td>
<td>
4
</td>
<td>
5
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
pref_talent_w1
</td>
<td>
491
</td>
<td>
3.41
</td>
<td>
1.24
</td>
<td>
1
</td>
<td>
3
</td>
<td>
4
</td>
<td>
4
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
pref_wpart_w1
</td>
<td>
491
</td>
<td>
2.79
</td>
<td>
1.19
</td>
<td>
1
</td>
<td>
2
</td>
<td>
3
</td>
<td>
4
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
pref_netw_w1
</td>
<td>
491
</td>
<td>
2.48
</td>
<td>
1.15
</td>
<td>
1
</td>
<td>
2
</td>
<td>
2
</td>
<td>
3
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
pref_effort_w2
</td>
<td>
491
</td>
<td>
3.88
</td>
<td>
1.20
</td>
<td>
1
</td>
<td>
3
</td>
<td>
4
</td>
<td>
5
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
pref_talent_w2
</td>
<td>
491
</td>
<td>
3.30
</td>
<td>
1.10
</td>
<td>
1
</td>
<td>
3
</td>
<td>
3
</td>
<td>
4
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
pref_wpart_w2
</td>
<td>
491
</td>
<td>
2.58
</td>
<td>
1.16
</td>
<td>
1
</td>
<td>
2
</td>
<td>
3
</td>
<td>
3
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
pref_netw_w2
</td>
<td>
491
</td>
<td>
2.32
</td>
<td>
1.04
</td>
<td>
1
</td>
<td>
2
</td>
<td>
2
</td>
<td>
3
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
pref_effort_w3
</td>
<td>
491
</td>
<td>
4.05
</td>
<td>
1.08
</td>
<td>
1
</td>
<td>
4
</td>
<td>
4
</td>
<td>
5
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
pref_talent_w3
</td>
<td>
491
</td>
<td>
3.45
</td>
<td>
1.09
</td>
<td>
1
</td>
<td>
3
</td>
<td>
3
</td>
<td>
4
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
pref_wpart_w3
</td>
<td>
491
</td>
<td>
2.53
</td>
<td>
1.14
</td>
<td>
1
</td>
<td>
2
</td>
<td>
3
</td>
<td>
3
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
pref_netw_w3
</td>
<td>
491
</td>
<td>
2.34
</td>
<td>
1.07
</td>
<td>
1
</td>
<td>
1
</td>
<td>
2
</td>
<td>
3
</td>
<td>
5
</td>
</tr>
<tr>
<td colspan="9" style="border-bottom: 1px solid black">
</td>
</tr>
</table>
<pre class="r"><code>corwide03a&lt;- polychoric(x = select(g03 ,starts_with(match = &quot;perc_&quot;)),na.rm = T)
corrplot(corwide03a$rho, type = &quot;upper&quot;, tl.col = &quot;black&quot;, tl.srt = 45,addCoef.col = &quot;black&quot;,diag = FALSE,tl.cex = 0.75)</code></pre>
<div class="figure" style="text-align: center">
<img src="prod_analysis-cfa_files/figure-html/unnamed-chunk-52-1.png" alt="Percepción" width="75%" />
<p class="caption">
Percepción
</p>
</div>
<pre class="r"><code>corwide03b&lt;- polychoric(x = select(g03 ,starts_with(match = &quot;pref_&quot;)),na.rm = T)
corrplot(corwide03b$rho, method = &quot;color&quot; ,type = &quot;upper&quot;, tl.col = &quot;black&quot;, tl.srt = 45,addCoef.col = &quot;black&quot;,diag = FALSE)</code></pre>
<div class="figure" style="text-align: center">
<img src="prod_analysis-cfa_files/figure-html/unnamed-chunk-52-2.png" alt="Preferencia" width="75%" />
<p class="caption">
Preferencia
</p>
</div>
</div>
<div id="muestra-completa" class="section level3" number="8.1.4">
<h3 number="8.1.4"><span class="header-section-number">8.1.4</span> Muestra completa</h3>
<pre class="r"><code>stargazer(select(wide02 ,starts_with(match = &quot;perc_&quot;), starts_with(&quot;pref_&quot;)),type = &quot;html&quot;, median = T,digits = 2)</code></pre>
<table style="text-align:center">
<tr>
<td colspan="9" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
Statistic
</td>
<td>
N
</td>
<td>
Mean
</td>
<td>
St. Dev.
</td>
<td>
Min
</td>
<td>
Pctl(25)
</td>
<td>
Median
</td>
<td>
Pctl(75)
</td>
<td>
Max
</td>
</tr>
<tr>
<td colspan="9" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
perc_effort_w1
</td>
<td>
1,448
</td>
<td>
3.24
</td>
<td>
1.38
</td>
<td>
1
</td>
<td>
2
</td>
<td>
3
</td>
<td>
4
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
perc_talent_w1
</td>
<td>
1,448
</td>
<td>
3.08
</td>
<td>
1.16
</td>
<td>
1
</td>
<td>
2
</td>
<td>
3
</td>
<td>
4
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
perc_wpart_w1
</td>
<td>
1,448
</td>
<td>
3.67
</td>
<td>
1.35
</td>
<td>
1
</td>
<td>
3
</td>
<td>
4
</td>
<td>
5
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
perc_netw_w1
</td>
<td>
1,448
</td>
<td>
3.79
</td>
<td>
1.23
</td>
<td>
1
</td>
<td>
3
</td>
<td>
4
</td>
<td>
5
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
perc_effort_w2
</td>
<td>
1,448
</td>
<td>
3.33
</td>
<td>
1.24
</td>
<td>
1
</td>
<td>
2
</td>
<td>
4
</td>
<td>
4
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
perc_talent_w2
</td>
<td>
1,448
</td>
<td>
3.13
</td>
<td>
1.09
</td>
<td>
1
</td>
<td>
2
</td>
<td>
3
</td>
<td>
4
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
perc_wpart_w2
</td>
<td>
1,448
</td>
<td>
3.54
</td>
<td>
1.33
</td>
<td>
1
</td>
<td>
3
</td>
<td>
4
</td>
<td>
5
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
perc_netw_w2
</td>
<td>
1,448
</td>
<td>
3.55
</td>
<td>
1.25
</td>
<td>
1
</td>
<td>
3
</td>
<td>
4
</td>
<td>
4
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
perc_effort_w3
</td>
<td>
1,448
</td>
<td>
3.50
</td>
<td>
1.20
</td>
<td>
1
</td>
<td>
3
</td>
<td>
4
</td>
<td>
4
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
perc_talent_w3
</td>
<td>
1,448
</td>
<td>
3.20
</td>
<td>
1.03
</td>
<td>
1
</td>
<td>
3
</td>
<td>
3
</td>
<td>
4
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
perc_wpart_w3
</td>
<td>
1,448
</td>
<td>
3.40
</td>
<td>
1.29
</td>
<td>
1
</td>
<td>
3
</td>
<td>
4
</td>
<td>
4
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
perc_netw_w3
</td>
<td>
1,448
</td>
<td>
3.45
</td>
<td>
1.24
</td>
<td>
1
</td>
<td>
3
</td>
<td>
4
</td>
<td>
4
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
pref_effort_w1
</td>
<td>
1,448
</td>
<td>
3.93
</td>
<td>
1.24
</td>
<td>
1
</td>
<td>
3
</td>
<td>
4
</td>
<td>
5
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
pref_talent_w1
</td>
<td>
1,448
</td>
<td>
3.31
</td>
<td>
1.18
</td>
<td>
1
</td>
<td>
3
</td>
<td>
3
</td>
<td>
4
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
pref_wpart_w1
</td>
<td>
1,448
</td>
<td>
2.70
</td>
<td>
1.18
</td>
<td>
1
</td>
<td>
2
</td>
<td>
3
</td>
<td>
4
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
pref_netw_w1
</td>
<td>
1,448
</td>
<td>
2.39
</td>
<td>
1.10
</td>
<td>
1
</td>
<td>
1.8
</td>
<td>
2
</td>
<td>
3
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
pref_effort_w2
</td>
<td>
1,448
</td>
<td>
3.93
</td>
<td>
1.16
</td>
<td>
1
</td>
<td>
3
</td>
<td>
4
</td>
<td>
5
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
pref_talent_w2
</td>
<td>
1,448
</td>
<td>
3.29
</td>
<td>
1.12
</td>
<td>
1
</td>
<td>
3
</td>
<td>
3
</td>
<td>
4
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
pref_wpart_w2
</td>
<td>
1,448
</td>
<td>
2.59
</td>
<td>
1.15
</td>
<td>
1
</td>
<td>
2
</td>
<td>
3
</td>
<td>
3
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
pref_netw_w2
</td>
<td>
1,448
</td>
<td>
2.30
</td>
<td>
1.05
</td>
<td>
1
</td>
<td>
1
</td>
<td>
2
</td>
<td>
3
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
pref_effort_w3
</td>
<td>
1,448
</td>
<td>
4.06
</td>
<td>
1.09
</td>
<td>
1
</td>
<td>
4
</td>
<td>
4
</td>
<td>
5
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
pref_talent_w3
</td>
<td>
1,448
</td>
<td>
3.46
</td>
<td>
1.07
</td>
<td>
1
</td>
<td>
3
</td>
<td>
4
</td>
<td>
4
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
pref_wpart_w3
</td>
<td>
1,448
</td>
<td>
2.53
</td>
<td>
1.15
</td>
<td>
1
</td>
<td>
2
</td>
<td>
3
</td>
<td>
3
</td>
<td>
5
</td>
</tr>
<tr>
<td style="text-align:left">
pref_netw_w3
</td>
<td>
1,448
</td>
<td>
2.32
</td>
<td>
1.07
</td>
<td>
1
</td>
<td>
1
</td>
<td>
2
</td>
<td>
3
</td>
<td>
5
</td>
</tr>
<tr>
<td colspan="9" style="border-bottom: 1px solid black">
</td>
</tr>
</table>
<pre class="r"><code>corwideA&lt;- polychoric(x = select(wide02 ,starts_with(match = &quot;perc_&quot;)),na.rm = T)
corrplot(corwideA$rho, method = &quot;color&quot; ,type = &quot;upper&quot;, tl.col = &quot;black&quot;, tl.srt = 45,addCoef.col = &quot;black&quot;,diag = FALSE)</code></pre>
<div class="figure" style="text-align: center">
<img src="prod_analysis-cfa_files/figure-html/unnamed-chunk-54-1.png" alt="Percepción" width="75%" />
<p class="caption">
Percepción
</p>
</div>
<pre class="r"><code>corwideB&lt;- polychoric(x = select(wide02 ,starts_with(match = &quot;pref_&quot;)),na.rm = T)
corrplot(corwideB$rho, method = &quot;color&quot; ,type = &quot;upper&quot;, tl.col = &quot;black&quot;, tl.srt = 45,addCoef.col = &quot;black&quot;,diag = FALSE)</code></pre>
<div class="figure" style="text-align: center">
<img src="prod_analysis-cfa_files/figure-html/unnamed-chunk-54-2.png" alt="Preferencia" width="75%" />
<p class="caption">
Preferencia
</p>
</div>
</div>
</div>
<div id="cfa-wave01-wave02-y-wave03" class="section level2" number="8.2">
<h2 number="8.2"><span class="header-section-number">8.2</span> CFA wave01, wave02 y wave03</h2>
<pre class="r"><code>model_long &lt;- &#39;
# wave 01
perc_merit1 =~perc_effort_w1+perc_talent_w1 
perc_nmerit1=~perc_wpart_w1 +perc_netw_w1  
pref_merit1 =~pref_effort_w1+pref_talent_w1 
pref_nmerit1=~pref_wpart_w1 +pref_netw_w1
# wave 02
perc_merit2 =~perc_effort_w2+perc_talent_w2 
perc_nmerit2=~perc_wpart_w2 +perc_netw_w2  
pref_merit2 =~pref_effort_w2+pref_talent_w2 
pref_nmerit2=~pref_wpart_w2 +pref_netw_w2
# wave 03
perc_merit3 =~perc_effort_w3+perc_talent_w3 
perc_nmerit3=~perc_wpart_w3 +perc_netw_w3  
pref_merit3 =~pref_effort_w3+pref_talent_w3 
pref_nmerit3=~pref_wpart_w3 +pref_netw_w3&#39;


fitlong_c &lt;- cfa(model = model_long,data = wide02,estimator=&quot;MLR&quot;) # Continuo/ estimador ML Robust

indicadores &lt;-c(&quot;perc_effort_w1&quot;,&quot;perc_talent_w1&quot;,&quot;perc_wpart_w1&quot;,&quot;perc_netw_w1&quot;,
                &quot;pref_effort_w1&quot;,&quot;pref_talent_w1&quot;,&quot;pref_wpart_w1&quot;,&quot;pref_netw_w1&quot;,
                &quot;perc_effort_w2&quot;,&quot;perc_talent_w2&quot;,&quot;perc_wpart_w2&quot;,&quot;perc_netw_w2&quot;,
                &quot;pref_effort_w2&quot;,&quot;pref_talent_w2&quot;,&quot;pref_wpart_w2&quot;,&quot;pref_netw_w2&quot;)  

fitlong_o &lt;- cfa(model = model_long,data = wide02,ordered = indicadores)

#---------------------------------------------------#
#summary(fitlong_c,standardized=TRUE, fit.measures=TRUE)
fitmeasures(fitlong_c)[c(&quot;chisq.scaled&quot;,&quot;df&quot;,&quot;cfi&quot;,&quot;cfi.scaled&quot;,&quot;cfi.robust&quot;,&quot;rmsea&quot;,&quot;rmsea.scaled&quot;,&quot;rmsea.robust&quot;)]
semPlot::semPaths(object = fitlong_c,what = &quot;std&quot;,thresholds = FALSE, intercepts = FALSE)</code></pre>
<p><img src="prod_analysis-cfa_files/figure-html/unnamed-chunk-55-1.png" width="672" /></p>
<pre class="r"><code>#summary(fitlong_o,standardized=TRUE, fit.measures=TRUE)
fitmeasures(fitlong_o)[c(&quot;chisq.scaled&quot;,&quot;df&quot;,&quot;cfi&quot;,&quot;cfi.scaled&quot;,&quot;cfi.robust&quot;,&quot;rmsea&quot;,&quot;rmsea.scaled&quot;,&quot;rmsea.robust&quot;)]
semPlot::semPaths(object = fitlong_o,what = &quot;std&quot;,thresholds = FALSE, intercepts = FALSE,style = &quot;mx&quot;)</code></pre>
<p><img src="prod_analysis-cfa_files/figure-html/unnamed-chunk-55-2.png" width="672" /></p>
<pre><code>## chisq.scaled           df          cfi   cfi.scaled   cfi.robust        rmsea rmsea.scaled 
## 665.88017314 186.00000000   0.93012912   0.92988159   0.93302455   0.04637638   0.04221100 
## rmsea.robust 
##   0.04525147 
## chisq.scaled           df          cfi   cfi.scaled   cfi.robust        rmsea rmsea.scaled 
## 747.48098303 186.00000000   0.98273020   0.94727999           NA   0.03597639   0.04567481 
## rmsea.robust 
##           NA</code></pre>
<pre class="r"><code>cormat&lt;- as.matrix(inspect(fitlong_o, &quot;cor.lv&quot;))
corrplot(cormat, method = &quot;color&quot; ,type = &quot;upper&quot;, tl.col = &quot;black&quot;, tl.srt = 45,addCoef.col = &quot;black&quot;,diag = FALSE)</code></pre>
<div class="figure">
<img src="prod_analysis-cfa_files/figure-html/unnamed-chunk-56-1.png" alt="Correlación entre variables latentes w01, w02 y w03" width="672" />
<p class="caption">
Correlación entre variables latentes w01, w02 y w03
</p>
</div>
</div>
</div>
<div id="invarianza" class="section level1" number="9">
<h1 number="9"><span class="header-section-number">9</span> Invarianza</h1>
<ol style="list-style-type: decimal">
<li>Invarianza entre modalidades en ola 1,2 y 3 (between groups invariance)</li>
<li>Invarianza entre tratamientos en ola 2(between groups invariance)</li>
</ol>
<blockquote>
<p><strong>NOTA</strong>: En vista de que no existe una librería que permita estimar invarianza longitudinal asumiendo indicadores ordinales, las primeras estimaciones las realizaré asumiendo indicadores continuos (estimator=ML).</p>
</blockquote>
<pre class="r"><code>library(semTools)</code></pre>
<pre class="r"><code>load(file = &quot;input/data/proc/datalong.RData&quot;)     # Datos formato long
load(file = &quot;input/data/proc/datawide_123.RData&quot;) # Datos formato long</code></pre>
<pre class="r"><code>dim(dat04)
m_inv_modalidad &lt;- &#39;perc_merit=~ perc_effort+perc_talent 
                    perc_nmerit=~perc_wpart +perc_netw  
                    pref_merit=~ pref_effort+pref_talent 
                    pref_nmerit=~pref_wpart +pref_netw&#39;

indicators  &lt;-c(&quot;perc_effort&quot;,&quot;perc_talent&quot;,&quot;perc_wpart&quot;,&quot;perc_netw&quot;,
                &quot;pref_effort&quot;,&quot;pref_talent&quot;,&quot;pref_wpart&quot;,&quot;pref_netw&quot;)  

fit.conf=cfa(m_inv_modalidad,data=dat04,group=&quot;grupo&quot;)
fit.deb =cfa(m_inv_modalidad,data=dat04,group=&quot;grupo&quot;,group.equal=c(&quot;loadings&quot;))
fit.fuer=cfa(m_inv_modalidad,data=dat04,group=&quot;grupo&quot;,group.equal=c(&quot;loadings&quot;,&quot;intercepts&quot;))
fit.str =cfa(m_inv_modalidad,data=dat04,group=&quot;grupo&quot;,group.equal=c(&quot;loadings&quot;,&quot;intercepts&quot;,&quot;residuals&quot;))


fitmeasures(fit.conf)[c(&quot;chisq.scaled&quot;,&quot;df&quot;,&quot;cfi&quot;,&quot;cfi.scaled&quot;,&quot;cfi.robust&quot;,&quot;rmsea&quot;,&quot;rmsea.scaled&quot;,&quot;rmsea.robust&quot;)]
fitmeasures(fit.deb )[c(&quot;chisq.scaled&quot;,&quot;df&quot;,&quot;cfi&quot;,&quot;cfi.scaled&quot;,&quot;cfi.robust&quot;,&quot;rmsea&quot;,&quot;rmsea.scaled&quot;,&quot;rmsea.robust&quot;)]
fitmeasures(fit.fuer)[c(&quot;chisq.scaled&quot;,&quot;df&quot;,&quot;cfi&quot;,&quot;cfi.scaled&quot;,&quot;cfi.robust&quot;,&quot;rmsea&quot;,&quot;rmsea.scaled&quot;,&quot;rmsea.robust&quot;)]
fitmeasures(fit.str )[c(&quot;chisq.scaled&quot;,&quot;df&quot;,&quot;cfi&quot;,&quot;cfi.scaled&quot;,&quot;cfi.robust&quot;,&quot;rmsea&quot;,&quot;rmsea.scaled&quot;,&quot;rmsea.robust&quot;)]
anova(fit.conf, fit.deb, fit.fuer, fit.str)</code></pre>
<pre><code>## [1] 2236   36
##        &lt;NA&gt;          df         cfi        &lt;NA&gt;        &lt;NA&gt;       rmsea        &lt;NA&gt;        &lt;NA&gt; 
##          NA 42.00000000  0.95494030          NA          NA  0.07575741          NA          NA 
##        &lt;NA&gt;          df         cfi        &lt;NA&gt;        &lt;NA&gt;       rmsea        &lt;NA&gt;        &lt;NA&gt; 
##          NA 50.00000000  0.94850216          NA          NA  0.07422755          NA          NA 
##        &lt;NA&gt;          df         cfi        &lt;NA&gt;        &lt;NA&gt;       rmsea        &lt;NA&gt;        &lt;NA&gt; 
##          NA 58.00000000  0.94733603          NA          NA  0.06969449          NA          NA 
##        &lt;NA&gt;          df         cfi        &lt;NA&gt;        &lt;NA&gt;       rmsea        &lt;NA&gt;        &lt;NA&gt; 
##          NA 74.00000000  0.91887795          NA          NA  0.07657891          NA          NA 
## Chi-Squared Difference Test
## 
##          Df   AIC   BIC  Chisq Chisq diff Df diff            Pr(&gt;Chisq)    
## fit.conf 42 52068 52578 214.03                                             
## fit.deb  50 52084 52549 246.61     32.579       8            0.00007332 ***
## fit.fuer 58 52081 52500 259.06     12.452       8                0.1321    
## fit.str  74 52173 52502 383.70    124.646      16 &lt; 0.00000000000000022 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>configural &lt;- &#39;
# wave 01
perc_merit1 =~NA*perc_effort_w1+lambda1*perc_effort_w1+perc_talent_w1 
perc_nmerit1=~NA*perc_wpart_w1 +lambda1*perc_wpart_w1 +perc_netw_w1  
pref_merit1 =~NA*pref_effort_w1+lambda1*pref_effort_w1+pref_talent_w1 
pref_nmerit1=~NA*pref_wpart_w1 +lambda1*pref_wpart_w1 +pref_netw_w1
# wave 02
perc_merit2 =~NA*perc_effort_w2+lambda1*perc_effort_w2+perc_talent_w2 
perc_nmerit2=~NA*perc_wpart_w2 +lambda1*perc_wpart_w2 +perc_netw_w2  
pref_merit2 =~NA*pref_effort_w2+lambda1*pref_effort_w2+pref_talent_w2 
pref_nmerit2=~NA*pref_wpart_w2 +lambda1*pref_wpart_w2 +pref_netw_w2
# wave 03
perc_merit3 =~NA*perc_effort_w3+lambda1*perc_effort_w3+perc_talent_w3 
perc_nmerit3=~NA*perc_wpart_w3 +lambda1*perc_wpart_w3 +perc_netw_w3  
pref_merit3 =~NA*pref_effort_w3+lambda1*pref_effort_w3+pref_talent_w3 
pref_nmerit3=~NA*pref_wpart_w3 +lambda1*pref_wpart_w3 +pref_netw_w3

# INTERCEPTS: Por cada variable latente, debo fijar el intercepto del primer indicador.
# wave 01--------------------------
perc_effort_w1 ~ i1*1   # Percepcion merito        
perc_talent_w1 ~ 1      #      
perc_wpart_w1 ~ i1*1    # Percepcion no-merito   
perc_netw_w1 ~ 1        #
pref_effort_w1 ~ i1*1   # Preferencia merito    
pref_talent_w1 ~ 1      #  
pref_wpart_w1 ~ i1*1    # Preferencia no-merito   
pref_netw_w1 ~ 1        #

# wave 02--------------------------
perc_effort_w2 ~ i1*1   # Percepcion merito                    
perc_talent_w2 ~ 1      #               
perc_wpart_w2 ~ i1*1    # Percepcion no-merito              
perc_netw_w2 ~ 1        #       
pref_effort_w2 ~ i1*1   # Preferencia merito                
pref_talent_w2 ~ 1      #           
pref_wpart_w2 ~ i1*1    # Preferencia no-merito              
pref_netw_w2 ~ 1        #       
               
# wave 03--------------------------
perc_effort_w3 ~ i1*1   # Percepcion merito                     
perc_talent_w3 ~ 1      #                            
perc_wpart_w3 ~ i1*1    # Percepcion no-merito                
perc_netw_w3 ~ 1        #                  
pref_effort_w3 ~ i1*1   # Preferencia merito                   
pref_talent_w3 ~ 1      #                        
pref_wpart_w3 ~ i1*1    # Preferencia no-merito               
pref_netw_w3 ~ 1        #

# UNIQUE VARIANCES and COVARIANCES.


# LATENT VARIABLES MEANS: Para cada variable latente fijar la media
# Fix T1 common factor mean to zero
perc_merit1 ~ 0*1
# Freely estimate T2-T3 common factor means
perc_merit2 ~ 1
perc_merit3 ~ 1

perc_nmerit1 ~ 0*1
perc_nmerit2 ~ 1
perc_nmerit3 ~ 1

pref_merit1 ~ 0*1
pref_merit2 ~ 1
pref_merit3 ~ 1

pref_nmerit1 ~ 0*1
pref_nmerit2 ~ 1
pref_nmerit3 ~ 1

# LATENT VARIABLE VARIANCES AND COVARIANCES: correlaciones entre variables latentes

&#39;                   

fit_conf &lt;- cfa(model = configural,data =wide02)
summary(fit_conf, standardized=TRUE)</code></pre>
<pre><code>## lavaan 0.6-5 ended normally after 87 iterations
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of free parameters                        158
##   Number of equality constraints                    22
##   Row rank of the constraints matrix                22
##                                                       
##   Number of observations                          1448
##                                                       
## Model Test User Model:
##                                                       
##   Test statistic                              1460.610
##   Degrees of freedom                               188
##   P-value (Chi-square)                           0.000
## 
## Parameter Estimates:
## 
##   Information                                 Expected
##   Information saturated (h1) model          Structured
##   Standard errors                             Standard
## 
## Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##   perc_merit1 =~                                                        
##     prc_f_1 (lmb1)    1.313    0.010  126.406    0.000    0.958    0.695
##     prc_t_1           1.013    0.060   16.823    0.000    0.739    0.636
##   perc_nmerit1 =~                                                       
##     prc_w_1 (lmb1)    1.313    0.010  126.406    0.000    1.134    0.808
##     prc_n_1           1.221    0.050   24.307    0.000    1.054    0.834
##   pref_merit1 =~                                                        
##     prf_f_1 (lmb1)    1.313    0.010  126.406    0.000    1.080    0.774
##     prf_t_1           0.880    0.050   17.469    0.000    0.724    0.596
##   pref_nmerit1 =~                                                       
##     prf_w_1 (lmb1)    1.313    0.010  126.406    0.000    1.019    0.772
##     prf_n_1           1.137    0.051   22.487    0.000    0.882    0.766
##   perc_merit2 =~                                                        
##     prc_f_2 (lmb1)    1.313    0.010  126.406    0.000    0.780    0.627
##     prc_t_2           1.091    0.068   16.033    0.000    0.648    0.593
##   perc_nmerit2 =~                                                       
##     prc_w_2 (lmb1)    1.313    0.010  126.406    0.000    0.979    0.736
##     prc_n_2           1.130    0.070   16.099    0.000    0.843    0.675
##   pref_merit2 =~                                                        
##     prf_f_2 (lmb1)    1.313    0.010  126.406    0.000    0.737    0.632
##     prf_t_2           1.301    0.075   17.407    0.000    0.730    0.648
##   pref_nmerit2 =~                                                       
##     prf_w_2 (lmb1)    1.313    0.010  126.406    0.000    0.766    0.657
##     prf_n_2           1.147    0.068   16.985    0.000    0.669    0.625
##   perc_merit3 =~                                                        
##     prc_f_3 (lmb1)    1.313    0.010  126.406    0.000    0.833    0.692
##     prc_t_3           1.005    0.058   17.346    0.000    0.638    0.621
##   perc_nmerit3 =~                                                       
##     prc_w_3 (lmb1)    1.313    0.010  126.406    0.000    1.005    0.774
##     prc_n_3           1.126    0.060   18.832    0.000    0.862    0.692
##   pref_merit3 =~                                                        
##     prf_f_3 (lmb1)    1.313    0.010  126.406    0.000    0.713    0.649
##     prf_t_3           1.230    0.071   17.380    0.000    0.668    0.617
##   pref_nmerit3 =~                                                       
##     prf_w_3 (lmb1)    1.313    0.010  126.406    0.000    0.886    0.761
##     prf_n_3           1.154    0.055   21.051    0.000    0.779    0.718
## 
## Covariances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##   perc_merit1 ~~                                                        
##     perc_nmerit1      0.010    0.023    0.414    0.679    0.015    0.015
##     pref_merit1       0.302    0.027   11.370    0.000    0.503    0.503
##     pref_nmerit1      0.150    0.023    6.628    0.000    0.265    0.265
##     perc_merit2       0.266    0.022   11.889    0.000    0.615    0.615
##     perc_nmerit2     -0.085    0.023   -3.768    0.000   -0.156   -0.156
##     pref_merit2       0.101    0.018    5.488    0.000    0.246    0.246
##     pref_nmerit2      0.092    0.019    4.860    0.000    0.216    0.216
##     perc_merit3       0.242    0.022   11.119    0.000    0.523    0.523
##     perc_nmerit3     -0.084    0.022   -3.727    0.000   -0.150   -0.150
##     pref_merit3       0.052    0.018    2.974    0.003    0.132    0.132
##     pref_nmerit3      0.123    0.020    6.130    0.000    0.249    0.249
##   perc_nmerit1 ~~                                                       
##     pref_merit1       0.388    0.028   13.904    0.000    0.546    0.546
##     pref_nmerit1     -0.077    0.023   -3.350    0.001   -0.114   -0.114
##     perc_merit2      -0.066    0.021   -3.229    0.001   -0.129   -0.129
##     perc_nmerit2      0.235    0.024    9.620    0.000    0.364    0.364
##     pref_merit2       0.134    0.019    6.974    0.000    0.276    0.276
##     pref_nmerit2     -0.068    0.019   -3.512    0.000   -0.136   -0.136
##     perc_merit3      -0.042    0.021   -2.018    0.044   -0.076   -0.076
##     perc_nmerit3      0.295    0.025   11.851    0.000    0.446    0.446
##     pref_merit3       0.135    0.019    7.231    0.000    0.288    0.288
##     pref_nmerit3     -0.082    0.020   -4.006    0.000   -0.140   -0.140
##   pref_merit1 ~~                                                        
##     pref_nmerit1     -0.118    0.024   -4.900    0.000   -0.184   -0.184
##     perc_merit2       0.049    0.021    2.285    0.022    0.100    0.100
##     perc_nmerit2      0.072    0.024    2.995    0.003    0.118    0.118
##     pref_merit2       0.215    0.021   10.324    0.000    0.466    0.466
##     pref_nmerit2     -0.047    0.020   -2.343    0.019   -0.099   -0.099
##     perc_merit3       0.092    0.022    4.243    0.000    0.176    0.176
##     perc_nmerit3      0.090    0.024    3.753    0.000    0.143    0.143
##     pref_merit3       0.204    0.020   10.148    0.000    0.456    0.456
##     pref_nmerit3     -0.034    0.021   -1.595    0.111   -0.061   -0.061
##   pref_nmerit1 ~~                                                       
##     perc_merit2       0.101    0.019    5.195    0.000    0.219    0.219
##     perc_nmerit2     -0.006    0.022   -0.264    0.791   -0.010   -0.010
##     pref_merit2      -0.051    0.018   -2.895    0.004   -0.117   -0.117
##     pref_nmerit2      0.327    0.022   14.825    0.000    0.722    0.722
##     perc_merit3       0.104    0.020    5.310    0.000    0.211    0.211
##     perc_nmerit3     -0.025    0.022   -1.181    0.238   -0.043   -0.043
##     pref_merit3      -0.059    0.017   -3.421    0.001   -0.139   -0.139
##     pref_nmerit3      0.334    0.022   15.010    0.000    0.638    0.638
##   perc_merit2 ~~                                                        
##     perc_nmerit2     -0.008    0.019   -0.392    0.695   -0.017   -0.017
##     pref_merit2       0.195    0.018   10.914    0.000    0.585    0.585
##     pref_nmerit2      0.097    0.017    5.806    0.000    0.279    0.279
##     perc_merit3       0.261    0.020   12.897    0.000    0.693    0.693
##     perc_nmerit3     -0.065    0.019   -3.356    0.001   -0.144   -0.144
##     pref_merit3       0.059    0.015    3.831    0.000    0.183    0.183
##     pref_nmerit3      0.098    0.017    5.630    0.000    0.243    0.243
##   perc_nmerit2 ~~                                                       
##     pref_merit2       0.195    0.019   10.028    0.000    0.465    0.465
##     pref_nmerit2      0.039    0.018    2.148    0.032    0.091    0.091
##     perc_merit3      -0.066    0.020   -3.335    0.001   -0.139   -0.139
##     perc_nmerit3      0.285    0.024   11.887    0.000    0.500    0.500
##     pref_merit3       0.092    0.017    5.231    0.000    0.226    0.226
##     pref_nmerit3     -0.032    0.019   -1.677    0.094   -0.064   -0.064
##   pref_merit2 ~~                                                        
##     pref_nmerit2      0.025    0.015    1.706    0.088    0.077    0.077
##     perc_merit3       0.097    0.016    5.974    0.000    0.272    0.272
##     perc_nmerit3      0.068    0.018    3.821    0.000    0.158    0.158
##     pref_merit3       0.198    0.016   12.190    0.000    0.649    0.649
##     pref_nmerit3     -0.008    0.016   -0.547    0.584   -0.022   -0.022
##   pref_nmerit2 ~~                                                       
##     perc_merit3       0.077    0.017    4.624    0.000    0.207    0.207
##     perc_nmerit3      0.032    0.018    1.729    0.084    0.071    0.071
##     pref_merit3      -0.002    0.014   -0.122    0.903   -0.006   -0.006
##     pref_nmerit3      0.287    0.020   14.702    0.000    0.729    0.729
##   perc_merit3 ~~                                                        
##     perc_nmerit3     -0.043    0.020   -2.200    0.028   -0.088   -0.088
##     pref_merit3       0.201    0.017   11.529    0.000    0.582    0.582
##     pref_nmerit3      0.129    0.018    7.291    0.000    0.302    0.302
##   perc_nmerit3 ~~                                                       
##     pref_merit3       0.187    0.018   10.117    0.000    0.450    0.450
##     pref_nmerit3      0.086    0.019    4.415    0.000    0.166    0.166
##   pref_merit3 ~~                                                        
##     pref_nmerit3     -0.016    0.015   -1.059    0.290   -0.044   -0.044
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##    .prc_ffr_1 (i1)    3.297    0.020  164.061    0.000    3.297    2.393
##    .prc_tln_1         3.066    0.029  106.525    0.000    3.066    2.638
##    .prc_wpr_1 (i1)    3.297    0.020  164.061    0.000    3.297    2.349
##    .prc_ntw_1         3.487    0.028  126.736    0.000    3.487    2.757
##    .prf_ffr_1 (i1)    3.297    0.020  164.061    0.000    3.297    2.362
##    .prf_tln_1         3.031    0.030  102.363    0.000    3.031    2.495
##    .prf_wpr_1 (i1)    3.297    0.020  164.061    0.000    3.297    2.500
##    .prf_ntw_1         2.730    0.026  103.746    0.000    2.730    2.369
##    .prc_ffr_2 (i1)    3.297    0.020  164.061    0.000    3.297    2.651
##    .prc_tln_2         3.105    0.036   86.433    0.000    3.105    2.840
##    .prc_wpr_2 (i1)    3.297    0.020  164.061    0.000    3.297    2.480
##    .prc_ntw_2         3.345    0.037   90.001    0.000    3.345    2.679
##    .prf_ffr_2 (i1)    3.297    0.020  164.061    0.000    3.297    2.829
##    .prf_tln_2         2.664    0.048   55.509    0.000    2.664    2.365
##    .prf_wpr_2 (i1)    3.297    0.020  164.061    0.000    3.297    2.828
##    .prf_ntw_2         2.919    0.043   67.281    0.000    2.919    2.728
##    .prc_ffr_3 (i1)    3.297    0.020  164.061    0.000    3.297    2.740
##    .prc_tln_3         3.043    0.033   91.359    0.000    3.043    2.962
##    .prc_wpr_3 (i1)    3.297    0.020  164.061    0.000    3.297    2.540
##    .prc_ntw_3         3.360    0.035   97.079    0.000    3.360    2.698
##    .prf_ffr_3 (i1)    3.297    0.020  164.061    0.000    3.297    3.003
##    .prf_tln_3         2.742    0.050   55.151    0.000    2.742    2.533
##    .prf_wpr_3 (i1)    3.297    0.020  164.061    0.000    3.297    2.830
##    .prf_ntw_3         3.002    0.040   75.414    0.000    3.002    2.768
##     perc_mrt1         0.000                               0.000    0.000
##     perc_mrt2         0.077    0.027    2.908    0.004    0.130    0.130
##     perc_mrt3         0.186    0.026    7.227    0.000    0.293    0.293
##     prc_nmrt1         0.000                               0.000    0.000
##     prc_nmrt2         0.124    0.029    4.295    0.000    0.167    0.167
##     prc_nmrt3        -0.001    0.028   -0.043    0.966   -0.002   -0.002
##     pref_mrt1         0.000                               0.000    0.000
##     pref_mrt2         0.378    0.026   14.769    0.000    0.673    0.673
##     pref_mrt3         0.476    0.025   19.175    0.000    0.876    0.876
##     prf_nmrt1         0.000                               0.000    0.000
##     prf_nmrt2        -0.378    0.024  -15.616    0.000   -0.649   -0.649
##     prf_nmrt3        -0.427    0.024  -17.828    0.000   -0.633   -0.633
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##    .perc_effort_w1    0.981    0.062   15.727    0.000    0.981    0.517
##    .perc_talent_w1    0.805    0.042   18.951    0.000    0.805    0.596
##    .perc_wpart_w1     0.685    0.053   12.871    0.000    0.685    0.348
##    .perc_netw_w1      0.488    0.044   11.017    0.000    0.488    0.305
##    .pref_effort_w1    0.782    0.066   11.911    0.000    0.782    0.401
##    .pref_talent_w1    0.951    0.044   21.535    0.000    0.951    0.644
##    .pref_wpart_w1     0.702    0.048   14.782    0.000    0.702    0.404
##    .pref_netw_w1      0.550    0.036   15.216    0.000    0.550    0.414
##    .perc_effort_w2    0.938    0.051   18.465    0.000    0.938    0.607
##    .perc_talent_w2    0.775    0.038   20.137    0.000    0.775    0.649
##    .perc_wpart_w2     0.810    0.063   12.792    0.000    0.810    0.458
##    .perc_netw_w2      0.850    0.052   16.344    0.000    0.850    0.545
##    .pref_effort_w2    0.816    0.042   19.295    0.000    0.816    0.600
##    .pref_talent_w2    0.735    0.040   18.482    0.000    0.735    0.580
##    .pref_wpart_w2     0.773    0.043   17.835    0.000    0.773    0.569
##    .pref_netw_w2      0.697    0.036   19.446    0.000    0.697    0.609
##    .perc_effort_w3    0.754    0.046   16.332    0.000    0.754    0.521
##    .perc_talent_w3    0.648    0.032   20.090    0.000    0.648    0.615
##    .perc_wpart_w3     0.675    0.054   12.439    0.000    0.675    0.401
##    .perc_netw_w3      0.808    0.046   17.407    0.000    0.808    0.521
##    .pref_effort_w3    0.698    0.038   18.416    0.000    0.698    0.579
##    .pref_talent_w3    0.726    0.036   20.016    0.000    0.726    0.619
##    .pref_wpart_w3     0.572    0.039   14.826    0.000    0.572    0.421
##    .pref_netw_w3      0.569    0.033   17.421    0.000    0.569    0.484
##     perc_merit1       0.532    0.044   12.096    0.000    1.000    1.000
##     perc_nmerit1      0.746    0.045   16.522    0.000    1.000    1.000
##     pref_merit1       0.677    0.049   13.783    0.000    1.000    1.000
##     pref_nmerit1      0.602    0.040   15.182    0.000    1.000    1.000
##     perc_merit2       0.353    0.033   10.627    0.000    1.000    1.000
##     perc_nmerit2      0.556    0.045   12.392    0.000    1.000    1.000
##     pref_merit2       0.315    0.028   11.229    0.000    1.000    1.000
##     pref_nmerit2      0.340    0.030   11.441    0.000    1.000    1.000
##     perc_merit3       0.403    0.033   12.101    0.000    1.000    1.000
##     perc_nmerit3      0.586    0.042   14.060    0.000    1.000    1.000
##     pref_merit3       0.295    0.026   11.403    0.000    1.000    1.000
##     pref_nmerit3      0.456    0.031   14.481    0.000    1.000    1.000</code></pre>
<ul>
<li><p>Invarianza Longitudinal en lavaan <a href="https://quantdev.ssri.psu.edu/tutorials/intro-basics-longitudinal-measurement-invariance" class="uri">https://quantdev.ssri.psu.edu/tutorials/intro-basics-longitudinal-measurement-invariance</a></p></li>
<li><p><a href="https://users.ugent.be/~yrosseel/lavaan/multiplegroup6Dec2012.pdf" class="uri">https://users.ugent.be/~yrosseel/lavaan/multiplegroup6Dec2012.pdf</a></p></li>
<li><p>Invarianza con indicadores categóricos <a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5121102/pdf/nihms757737.pdf" class="uri">https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5121102/pdf/nihms757737.pdf</a></p></li>
<li><p>Parametrización tetha: <a href="https://groups.google.com/forum/#!topic/lavaan/nfdatPgLLhc" class="uri">https://groups.google.com/forum/#!topic/lavaan/nfdatPgLLhc</a></p></li>
<li><p>Colapsing categories: <a href="https://www.tandfonline.com/doi/abs/10.1080/10705511.2018.1547640?journalCode=hsem20" class="uri">https://www.tandfonline.com/doi/abs/10.1080/10705511.2018.1547640?journalCode=hsem20</a></p></li>
</ul>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("hide" === "show");
});
</script>

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3,h4",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
